Add: Upgrade voices for Satellite Hack 1 and 2
TheSuperHackers/GeneralsGamePatch pull request #1262
Opened 2022-09-23 12:10 UTC by Stubbjax

The Satellite Hack upgrades now each have their own EVA audio events, instead of the generic "Upgrade complete" line.

https://user-images.githubusercontent.com/11547761/191956466-2faafe80-274c-4fc0-8873-05f6c67e6168.mp4

2022-09-23 13:35 UTC, ImTimK commented
Sexy

2022-09-23 14:14 UTC, xezon commented
Are the sounds in their respective languages? Also what happens if USA player has Internet Center? Do we expect USA EVA voice as opposed to China EVA voice?

2022-09-23 14:27 UTC, Stubbjax commented
> Are the sounds in their respective languages? Also what happens if USA player has Internet Center? Do we expect USA EVA voice as opposed to China EVA voice?

Hmm, that's a good question. How does it work for the other EVA events that @commy2 added in #1026? The localised variants would have to be done by those familiar with those languages to ensure the correct sentence structure, assuming the respective audio exists for them.

2022-09-23 14:33 UTC, xezon commented
German, French, Russian can be sourced from locales.

2022-09-23 15:02 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Voice.ini
> +End
```suggestion
End

````
Minor nitpick, all lines should end with a /n character,

2022-09-23 15:03 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/INI/Voice.ini
> +End
Ah yeah, I did notice that but forgot about it.

2022-09-23 15:04 UTC, commy2 approved these changes
neat 👍

2022-09-23 15:05 UTC, xezon commented
Please do not merge until sounds are sorted.

2022-09-23 15:05 UTC, commy2 requested changes, later dismissed
sort out sounds first

2022-09-23 15:05 UTC, Stubbjax commented
Aha I wasn't planning to. Just review the PR as `Changes Requested`!

2022-09-23 15:08 UTC, xezon commented
Additionally, I think we should isolate this change first:
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/1061/commits/71f3bedc8a00510fdc4b2852685f77531a09c566#diff-e8bc6bb844a8f9f70ca66bb955fa3c2cafd736d83bc906c104bc15fdbc942cca

It simplifies how sounds are sourced to avoid English copies. We can extract this commit from #1061 and submit first. If you cannot do this on your own, let me know I will do it.

2022-09-23 15:11 UTC, Stubbjax commented
Ah right, didn't see that. It did feel very dirty copying the files, but #1026 was approved and merged that way so I matched the process. Is #1061 awaiting anything in particular?

2022-09-23 15:17 UTC, xezon commented
#1061 has not been reviewed. To review, one needs to listen to 1000 sounds. I doubt anyone will do that, so eventually I will just merge it in the future.

2022-09-23 15:46 UTC, Stubbjax commented
Alright, so to clarify, cherry-pick commit https://github.com/TheSuperHackers/GeneralsGamePatch/pull/1061/commits/71f3bedc8a00510fdc4b2852685f77531a09c566#diff-e8bc6bb844a8f9f70ca66bb955fa3c2cafd736d83bc906c104bc15fdbc942cca and remove the duplicate audio files from the non-English localisation directories?

2022-09-23 16:27 UTC, xezon commented
Yea, that commit can be its own PR. Once that is committed, we do not need to make English copies.

2022-09-23 16:43 UTC, Stubbjax commented
> Yea, that commit can be its own PR. 

You will open a dedicated PR?

2022-09-24 07:18 UTC, xezon commented
Commit #1273 before this one.

Also regarding English sounds, we should use the cleaned sounds from #1061, not the original ones.

2022-09-24 18:55 UTC, commy2 commented
lgtm

2022-09-24 19:03 UTC, xezon commented
It is still missing German, French, Russian, new English. I can add it if no one beats me to it.

2023-04-11 17:58 UTC, xezon commented
> Also what happens if USA player has Internet Center? Do we expect USA EVA voice as opposed to China EVA voice?

I think it is fine if voice is different. When buying Rocket Buggy Ammo as a USA for example then we also hear the GLA Buggy voice.

> The Satellite Hack upgrades now each have their own EVA audio events, instead of the generic "Upgrade complete" line.

Where are these sound files sourced from? I can not find these in original game files.

2023-04-12 06:39 UTC, commy2 commented
Same place MOAB and Fortified Structures sound if from. It's in a different folder for some reason.

2023-04-12 06:46 UTC, xezon commented
I was unable to locate it in all folders. Therefore I also do not know where it is for the other languages. Perhaps it is under a different name? If there is no same audio for German and French then we cannot use this.

2023-04-12 17:29 UTC, xezon commented
Here are all the EC files I have access to:

```
ecaactpc.wav
ecabuink.wav
ecabuipc.wav
ecabuiss.wav
ecallreq.wav
ecallyu.wav
ecanklau.wav
ecasslau.wav
ecbasof.wav
ecbasun.wav
ecbeaco.wav
ecblackd.wav
ecbuica.wav
ecbuildg.wav
ecbuilo.wav
ecbuiof.wav
ecbuion.wav
ecbuist.wav
eccapbla.wav
eccapbui.wav
eccapcol.wav
eccapher.wav
eccapjar.wav
eccashs.wav
eccolbud.wav
ecconst.wav
ecdeant.wav
ecdedai.wav
ecdeemp.wav
ecdefue.wav
ecdenuk.wav
ecdepar.wav
ecdescu.wav
eceblacd.wav
ececolbd.wav
ecejarmd.wav
ecempmup.wav
ecfunds.wav
eciobecl.wav
eciocacs.wav
eciocril.wav
eciodecs.wav
eciodesg.wav
eciodess.wav
eciodest.wav
eciofall.wav
ecioproc.wav
eciorise.wav
ecioverl.wav
ecjarmkd.wav
eclagpss.wav
eclanuk.wav
eclapar.wav
eclascu.wav
eclasnea.wav
eclevel.wav
ecneutup.wav
ecnuklau.wav
ecnukrea.wav
econline.wav
ecparact.wav
ecparrea.wav
ecpldef.wav
ecplvic.wav
ecpower.wav
ecrecfnd.wav
ecreinf.wav
ecscdlau.wav
ecscurea.wav
ecselec.wav
ecstrong.wav
ectraing.wav
ectrnfnd.wav
ecunitl.wav
ecunitp.wav
ecunitr.wav
ecupgra.wav
ecvehst.wav
ecyoureq.wav
```

2023-05-07 13:58 UTC, xezon commented
I have remade the English sounds. And made French, German ones too. And added default Upgrade sound for Russian. Documentation added. Sounds good.

2023-05-07 14:04 UTC, xezon commented
Fixed one small error in French sound.

2023-05-07 14:04 UTC, xezon approved these changes

2023-05-07 14:05 UTC, merged