US localization fixes and improvements
TheSuperHackers/GeneralsGamePatch pull request #2535
Opened 2024-11-06 16:51 UTC by xezon

US localization fixes and improvements

2024-11-22 14:34 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 21/11/2024 US Change Mistake fix (#2535)
I suggest to document these as `Changes US from "unknown server"`

2024-12-09 19:35 UTC, xezon reviewed
Overall: This language edit does too many different things. There are some edits, where I have asked if other languages have been tweaked as well, which would be better suited for separate changes where all languages are edited in one go.

Why? Because it makes it much easier to review, and classify as a single change, aka it is easier to see in the commit history, easier to revert and also easier to create a matching yaml file with change descriptions for.

Here is an example of how a change that touches one specific thing:

https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2352/files

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Cannon: &C" (#2535)
Please verify the original String. It must have been something like "Gattling &Cannon"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Tank: &C" (#2535)
Probably without ": &C"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Tank: &C" (#2535)
Please verify the original String. It must have been something like "&Gattling Cannon". Several times.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Terrorist Cell"
I think "Terror Cell" is correct.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Tank: &C" (#2535)
Remove this comment and add pull number to `@feature` above.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -US: "Iraqi War Zone\nOperation: Final Justice"
Are you sure this is incorrect? Could be correct.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Build a Gattling Cannon on this tank" (#2535)
Remove this comment and add pull number to `@feature` comment above.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Build a Gattling Cannon on this Overlord" (#2535)
This is not the original wording. See change #2324.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "This Bomb Truck becomes a biowar weapon with 25% more range" (#2535)
This may not be the original US text. See `@fix` above.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "US fence system. Laser-sensors give an alert when enemy troops are moving through the fence. Fence blocks enemy vehicle movement"
Maybe "Laser-sensors alert when enemy troops move through the fence."

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Commands special weapons. Creates Construction Dozers. Grants ability to deploy a Radar"
USA HQ says "Provides radar"

Perhaps word this as "Deploys radar"

It is not optimal that this pull just edits English for changes like this one. Ideally there was a single change that edited all languages of `CONTROLBAR:ToolTipChinaBuildCommandCenter` to add the missing sentence. Now, this is difficult to review, because we cannot see all language edits at once. So if in another language edit this fix is missing or worded incorrectly, then we would not be able to see it in the review :(

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Camouflaged while not moving. Spots hidden enemies\n\nStrong vs. infantry\nWeak vs. light vehicles, scouts"
Is this fixed in the other languages as well?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Repairs vehicles and heals soldiers nearby. Cleans up radiation and toxins"
Is this also fixed for the other languages? I see French and Spanish for example are missing vehicle info.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Creates a fire-storm by attacking in a full group\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
The original text looks correct to me.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Creates a fire-storm by firing in a group\n\nStrong vs. base defenses, infantry\nWeak vs. tanks, aircraft"
The original text looks correct to me.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Nuke Cannons lob small tactical nukes great distances\n\nBuild at: War Factory" (#2535)
Is this text as original? Check #2166.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Allows you to create a surprise ambush of Rebels with charges anywhere\n\nRank 1: 4 Rebels\nRank 2: 6 Rebels\nRank 3: 10 Rebels\n\nDeploy from: Command Center"
Why "with charges"? Original text looks correct to me.

But, it would be nice to improve sentences that say "you".

So for example instead of "Allows you to create a surprise ambush of Rebels anywhere" it could say "Creates a surprise ambush of Rebels anywhere", which is more concise.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Anthrax bomb is deadly against enemy troop concentrations\n\nDeploy from: Command Center"
Original text looks ok. It talks about the Anthrax from the bomb, not the bomb itself.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "OutHouse"
This reads strange.

Perhaps call it "Loo"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Chinese-Occupied Jambul, Kazakhstan\nOperation: Righteous Fire"
Perhaps Zhambyl ?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Upgrades are bought at different structures in your base. They improve your unit's abilities. Left click on the Barracks and then left click on Capture Building icon to upgrade your Rangers to b
Original "They improve your units." looks ok to me.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "QuickMatch will attempt to match you based on skill level, connection quality, etc"
I would not count on "connection quality" until it is technically verified (I do not know). "PC spec" is ok.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Third Campaign"
What was the motivation for this change?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Fair Play Honor\nDisconnects from Online games accounts for less than 10% of total played games (at least 10 games required to be played) to earn this medal"
Original sentence is better.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Fair Play Honor\nDisconnects from Online games accounts for less than 10% of total played games (at least 10 games required to be played) to earn this medal"
Original sentence is better.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Create a formation of the selected units and they will retain moving order and speed of the slowest unit in formation on the move"
Original sentence is ok and concise.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Jambul"
Perhaps "Zhambyl" ?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "First Campaign"
What was the motivation for this change?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "ADVANCED GRAPHICS SETTINGS"
So it only really shows graphics options yes?

Was this fixed for all languages?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Show Units Behind Buildings"
Does this fit well in the GUI?

Was this tweaked for all languages?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Toggle displaying game props. Turn off for improved performance" (#2535)
Comment is misplaced.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Toggle displaying additional game props. Turn off for improved performance"
Why "additional"?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "VFX QUALITY"
"PARTICLE CAP" is more descriptive than "VFX QUALITY", because what is "vfx"? What is "quality"?

Particle cap means there is a particle number cap (the slider)

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "High quality texture resolution can slow down the game"
I would say "Higher resolution textures can slow down the game"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "High Quality (Slower)"
I think original label is fine.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Low Quality (Faster)"
I think original label is fine.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "High quality visual effects can slow down the game"
"More particles can slow down the game"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Toggle showing 3D shadows in game. Turn off for improved performance. Can cause a game crash when a lot of object's shadows are drawn in the scene"
I recommend to not yet document this problem here, because we do aim to fix the shadow crash.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Disable automatic detail adjustment(LOD). Turn off for improved performance"
Put a space before `(LOD)`

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Thanks to Bing Gordon, your continued support has been invaluable." (#2535)
You can document this under the general punctuation fixes. See "Fixes punctuation inconsistencies"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "One or more players have been disconnected from the game. If you choose to vote a person out of the game then click the VOTE button next to the respective player. When the timer counts down to 0
Should it be "be automatically removed" or "automatically be removed"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "It is possible that the person is attempting to reconnect so you may choose to wait until this player's timer has elapsed. When the timer counts down to 0 that person will be automatically remov
Should it be "be automatically removed" or "automatically be removed"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Select whether or not this game's statistics will be uploaded to the official C&C Generals Zero Hour server"
"recorded at" is fine. Keep in mind, if you change English, other languages would need to be changed too, so prefer to not change English wording unless very necessary.

Several times in this file.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Domination Honor\nPlayer has won over 10000 Skirmish games"
10,000 is not wrong. The comma is just a visual aid for thousands. What was the reason to change this? Are there inconsistencies?

I suggest create a separate change with a pass on > 1000 numbers style inconsistencies for all languages for a more systematic approach to this.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "US Air Force General"
This is quite a big change because historically this always has been USA and all players got used to this in 20 years. I recommend to leave USA as is in most strings.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "gattling" to "gatling" (#2535)
Original text was not "gattling".

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Combat Motorcycle: &Y"
Perhaps leave it as Cycle even if not stricly correct.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Nuclear Shells: &N"
Is this also fixed for the other languages?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nPurchase the Sentry Done gun from the War Factory"
Is this also fixed in the other languages?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Microwave Tank's microwave field will damage enemy infantry that come into its affected area"
Complicated.

Better: "The Microwave Tank fries nearby infantry"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Avenger laser can 'paint' enemy targets\nIt allows all friendly units nearby to have increased firing speed at the target"
Complicated.

Better: "Allied units attack painted targets with increased fire rate."

Was this adjusted for the other languages as well?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nAvengers are support vehicles that can protect themselves and nearby units from rocket attacks and defend against enemy aircraft"
Complicated.

Better: "Avengers are support units that can neutralize missiles and attack aircraft"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the Leaflet Drop to disable enemy units"
Is this also fixed in the other languages?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Stealth Bomber's Bunker Buster upgrade can kill garrisoned enemies"
Is this also fixed in the other languages?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Supply Lines upgrade improves income from resource gathering and drop zones"
Qualifiers may be inaccurate. Supply Lines also boosts Oil Derrick income. And perhaps Black Market income? Original text was very general, which is fine.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the Frenzy General's Power to increase the firepower and armor of your units for a limited time"
This qualifier makes a lot of sense.

Better: "Use the Frenzy General's Power to temporarily increase the firepower and armor of your units"

Is this also fixed in the other languages?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nSatellite Hack 2 reveals all that enemy units can see, for a small amount of time"
Better: "Satellite Hack 2 temporarily reveals all that enemy units can see"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse Sneak Attack to instantly create a Tunnel Network point anywhere you can see"
Better: "Use Sneak Attack to instantly create a Tunnel Network anywhere you can see"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the GPS Scrambler General's Power to camouflage friendly units"
There are a lot of "Generals Power(s)" in original text. Perhaps leave as is or make them all consistent. I think "Generals Power" is good.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "gattling" to "gatling" (#2535)
Capital G

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "gattling" to "gatling" (#2535)
Capital G

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Detonation ability enables all units to detonate after death or at your command"
It is called "Demolitions ability"

Original sentence is fine.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "+25% rate of fire for Mini-Gunners and Tank Hunters"
Was this adjusted for all similar tool tips?:

CONTROLBAR:TooltipChinaUpgradeNationalism
CONTROLBAR:TooltipChinaUpgradeFanaticism
CONTROLBAR:Boss_TooltipChinaUpgradeNationalism

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Ground defense. Can be garrisoned by four infantry"
Original text looks ok.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Heavy lift transport\nCan be upgraded with defense and support structures and Napalm Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
Previous text looks ok.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Heavy lift transport\nCan upgrade with base defense structures and Napalm Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, ant
This is not original text. See #2261.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "gattling" to "gatling" (#2535)
Capital G

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Causes your units to do more damage for a time when targeted\n\nRank 1: 10% for 10 seconds\nRank 2: 20% for 20 seconds\nRank 3: 30% for 30 seconds\n\nDeploy from: Command Center"
Perhaps should be written as "+10% damage ..."

Also better: "Temporarily increases damage of targeted units"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Where are my troops? Please let me go, OK? Don't hurt me!"
Is this also fixed in other languages?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "We have nice uniforms... come and see us... you will like it.\nOr not"
Is this also fixed in other languages?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "While the GLA has no need for power, China and the USA eat it up like popcorn. To keep a base running strong a General needs to spend money on plenty of power to supply the war machine. Make sur
"To keep a base running strong, [comma] a General needs to spend money on plenty of power to supply the war machine."

Better: "Running on low power puts your production and defenses at a disadvantage"

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Toggle showing heat distortion effects. Turn off for improved performance. Can cause visual glitches, such as drawing a black scene"
We aim to fix this problem. Perhaps do not put this here yet for all languages.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Heavy lift transport\nCan be upgraded with defense and support structures and Nuke Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
Previous text looks ok.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Heavy lift assault transport\nComes with Bunker upgrade and can install Napalm Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
Previous text looks ok. Also: Inf Helix does not come with Bunker preinstalled.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "WARNING:\nDr. Thrax has been known to use a Sneak Attack\n to surprise enemies"
No space after \n

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Nuke Carpet Bomber"
Oddly, the other China Bomber appears to be called "Carpet Bomb". Perhaps make a pass on that.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Nuke Bomber: &T" (#2535)
This is not the original text

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Super-sonic attack makes Aurora immune to enemy fire. After super-sonic attack, Aurora speed is reduced to 50%. Equipped with a Point Defense Las
This is not the original text.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Stealthed\nEquipped with a Point Defense Laser\n\nStrong vs. base defenses\nWeak vs. rocket soldiers"
This this also tweaked for the other languages?

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Update list of games and players"
All the missing strings added here ideally are done in a separate change for all languages in one go.

2024-12-09 19:35 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Clear"
Strings can be borrowed from GUI:Clear

2024-12-10 10:28 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Cannon: &C" (#2535)
Original string from main - Gattling Cannon: &C

2024-12-10 10:28 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Cannon: &C" (#2535)
Original string from main - Gattling Cannon: &C

2024-12-10 10:29 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Tank: &C" (#2535)
Fixed

2024-12-10 10:31 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Tank: &C" (#2535)
fixed, Original string from main - Gattling Tank: &G

2024-12-10 10:32 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Terrorist Cell"
Fixed

2024-12-10 10:34 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Cannon: &C" (#2535)
String in main is not original. Original string is the one in generals.csf from Original Zero hour Patch 1.04. You need to look at file from before this line was edited the first time in this file.

`: &C` key format was added by us.

2024-12-10 10:35 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Build a Gattling Cannon on this tank" (#2535)
fixed

2024-12-10 10:39 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Build a Gattling Cannon on this Overlord" (#2535)
Original string from main - Build a Gattling Cannon on this Overlord
Translated from German - Equip this Overlord with a Gatling gun
Which one to pick?

2024-12-10 10:39 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Tank: &C" (#2535)
fixed

2024-12-10 10:40 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -US: "Iraqi War Zone\nOperation: Final Justice"
fixed

2024-12-10 10:43 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "This Bomb Truck becomes a biowar weapon with 25% more range" (#2535)
Original string from main - This Bomb Truck becomes a biowar weapon with 25% more range
My edit - This Bomb Truck becomes a bioweapon and improves its explosion range by 25%
Which to pick?

2024-12-10 10:44 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "US fence system. Laser-sensors give an alert when enemy troops are moving through the fence. Fence blocks enemy vehicle movement"
Fixed

2024-12-10 10:47 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Commands special weapons. Creates Construction Dozers. Grants ability to deploy a Radar"
fixed, I will add this change to all other languages

2024-12-10 10:48 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Camouflaged while not moving. Spots hidden enemies\n\nStrong vs. infantry\nWeak vs. light vehicles, scouts"
I will make sure of it

2024-12-10 10:48 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Repairs vehicles and heals soldiers nearby. Cleans up radiation and toxins"
I will make sure of it

2024-12-10 10:49 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Creates a fire-storm by attacking in a full group\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
Fixed

2024-12-10 10:51 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Cannon: &C" (#2535)
Huh, so I need to find the original string and put it in place of my edit commentary?

2024-12-10 11:45 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Creates a fire-storm by firing in a group\n\nStrong vs. base defenses, infantry\nWeak vs. tanks, aircraft"
fixed

2024-12-10 11:47 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Allows you to create a surprise ambush of Rebels with charges anywhere\n\nRank 1: 4 Rebels\nRank 2: 6 Rebels\nRank 3: 10 Rebels\n\nDeploy from: Command Center"
fixed

2024-12-10 11:47 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Anthrax bomb is deadly against enemy troop concentrations\n\nDeploy from: Command Center"
fixed

2024-12-10 11:48 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "OutHouse"
fixed

2024-12-10 11:50 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Chinese-Occupied Jambul, Kazakhstan\nOperation: Righteous Fire"
Maybe this one? Its from original name - OBJECT:Zambul

2024-12-10 11:51 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Upgrades are bought at different structures in your base. They improve your unit's abilities. Left click on the Barracks and then left click on Capture Building icon to upgrade your Rangers to b
fixed

2024-12-10 11:52 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "QuickMatch will attempt to match you based on skill level, connection quality, etc"
fixed

2024-12-10 11:53 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Third Campaign"
fixed

2024-12-10 11:54 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Fair Play Honor\nDisconnects from Online games accounts for less than 10% of total played games (at least 10 games required to be played) to earn this medal"
fixed

2024-12-10 11:55 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Fair Play Honor\nDisconnects from Online games accounts for less than 10% of total played games (at least 10 games required to be played) to earn this medal"
fixed

2024-12-10 11:56 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Create a formation of the selected units and they will retain moving order and speed of the slowest unit in formation on the move"
fixed

2024-12-10 11:56 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Jambul"
fixed

2024-12-10 11:57 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "First Campaign"
fixed

2024-12-10 11:59 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "ADVANCED GRAPHICS SETTINGS"
It shows both of them, Display and Graphics options. The reason for this change is to modernize it, because in modern games we have graphics settings menu which also includes display ones.
I will make sure its for all languages if you approve the change

2024-12-10 12:05 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "ADVANCED GRAPHICS SETTINGS"
Yes
I will make sure of it
![image](https://github.com/user-attachments/assets/d21e9d75-1334-4552-a425-11f78e30566e)

2024-12-10 12:06 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Show Units Behind Buildings"
Yes
I will make sure of it
![image](https://github.com/user-attachments/assets/6c80e39c-04c1-4fc5-bf2c-07ba81c01736)

2024-12-10 12:07 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Toggle displaying game props. Turn off for improved performance" (#2535)
fixed

2024-12-10 12:10 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Toggle displaying additional game props. Turn off for improved performance"
If you turn it off you will have no props at all?

2024-12-10 12:10 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "VFX QUALITY"
fixed

2024-12-10 12:11 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "High quality texture resolution can slow down the game"
fixed

2024-12-10 12:12 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "High Quality (Slower)"
fixed

2024-12-10 12:12 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Low Quality (Faster)"
fixed

2024-12-10 12:12 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "High quality visual effects can slow down the game"
fixed

2024-12-10 12:13 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Toggle showing 3D shadows in game. Turn off for improved performance. Can cause a game crash when a lot of object's shadows are drawn in the scene"
fixed

2024-12-10 12:14 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Disable automatic detail adjustment(LOD). Turn off for improved performance"
fixed

2024-12-10 12:17 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Thanks to Bing Gordon, your continued support has been invaluable." (#2535)
fixed

2024-12-10 12:20 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "One or more players have been disconnected from the game. If you choose to vote a person out of the game then click the VOTE button next to the respective player. When the timer counts down to 0
I checked both variants here and they are both correct https://languagetool.org/

2024-12-10 12:20 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "It is possible that the person is attempting to reconnect so you may choose to wait until this player's timer has elapsed. When the timer counts down to 0 that person will be automatically remov
I checked both variants here and they are both correct https://languagetool.org/

2024-12-10 12:21 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Select whether or not this game's statistics will be uploaded to the official C&C Generals Zero Hour server"
fixed

2024-12-10 12:22 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Domination Honor\nPlayer has won over 10000 Skirmish games"
fixed

2024-12-10 12:23 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "US Air Force General"
fixed

2024-12-10 12:31 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Combat Motorcycle: &Y"
fixed

2024-12-10 12:32 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Nuclear Shells: &N"
I will make sure of it

2024-12-10 12:32 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nPurchase the Sentry Done gun from the War Factory"
I will make sure of it

2024-12-10 12:33 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Microwave Tank's microwave field will damage enemy infantry that come into its affected area"
fixed

2024-12-10 12:35 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Avenger laser can 'paint' enemy targets\nIt allows all friendly units nearby to have increased firing speed at the target"
fixed

2024-12-10 12:35 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nAvengers are support vehicles that can protect themselves and nearby units from rocket attacks and defend against enemy aircraft"
fixed

2024-12-10 12:36 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the Leaflet Drop to disable enemy units"
I will make sure of it

2024-12-10 12:36 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Stealth Bomber's Bunker Buster upgrade can kill garrisoned enemies"
I will make sure of it

2024-12-10 12:36 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Supply Lines upgrade improves income from resource gathering and drop zones"
fixed

2024-12-10 12:38 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the Frenzy General's Power to increase the firepower and armor of your units for a limited time"
Fixed
I will make sure of it

2024-12-10 12:38 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nSatellite Hack 2 reveals all that enemy units can see, for a small amount of time"
fixed

2024-12-10 12:39 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse Sneak Attack to instantly create a Tunnel Network point anywhere you can see"
Fixed

2024-12-10 12:40 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the GPS Scrambler General's Power to camouflage friendly units"
fixed

2024-12-10 12:41 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "gattling" to "gatling" (#2535)
fixed

2024-12-10 12:42 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "gattling" to "gatling" (#2535)
fixed

2024-12-10 12:42 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Detonation ability enables all units to detonate after death or at your command"
fixed

2024-12-10 12:46 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "+25% rate of fire for Mini-Gunners and Tank Hunters"
Now it is

2024-12-10 12:46 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Ground defense. Can be garrisoned by four infantry"
fixed

2024-12-10 12:47 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Heavy lift transport\nCan be upgraded with defense and support structures and Napalm Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
fixed

2024-12-10 12:49 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Causes your units to do more damage for a time when targeted\n\nRank 1: 10% for 10 seconds\nRank 2: 20% for 20 seconds\nRank 3: 30% for 30 seconds\n\nDeploy from: Command Center"
fixed

2024-12-10 12:51 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Where are my troops? Please let me go, OK? Don't hurt me!"
Yes, in google translate. I added translations for all localizations

2024-12-10 12:51 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "We have nice uniforms... come and see us... you will like it.\nOr not"
Yes, in google translate. I added translations for all localizations

2024-12-10 12:52 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "While the GLA has no need for power, China and the USA eat it up like popcorn. To keep a base running strong a General needs to spend money on plenty of power to supply the war machine. Make sur
fixed

2024-12-10 12:53 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Toggle showing heat distortion effects. Turn off for improved performance. Can cause visual glitches, such as drawing a black scene"
fixed

2024-12-10 12:53 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Heavy lift transport\nCan be upgraded with defense and support structures and Nuke Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
fixed

2024-12-10 12:54 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Heavy lift assault transport\nComes with Bunker upgrade and can install Napalm Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
fixed

2024-12-10 12:57 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "WARNING:\nDr. Thrax has been known to use a Sneak Attack\n to surprise enemies"
fixed

2024-12-10 12:57 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Nuke Carpet Bomber"
No edits necessary?

2024-12-10 12:58 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Stealthed\nEquipped with a Point Defense Laser\n\nStrong vs. base defenses\nWeak vs. rocket soldiers"
I will make sure of it

2024-12-10 13:01 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Update list of games and players"
Will do

2024-12-10 13:01 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Clear"
fixed

2024-12-11 07:42 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Cannon: &C" (#2535)
fixed

2024-12-11 07:43 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Tank: &C" (#2535)
fixed

2024-12-11 07:45 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Build a Gattling Cannon on this Overlord" (#2535)
original string from original str - Build a Gattling Cannon on this Overlord

2024-12-11 07:45 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Build a Gattling Cannon on this Overlord" (#2535)
original string from original str - Build a Gattling Cannon on this Overlord

2024-12-11 07:47 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "This Bomb Truck becomes a biowar weapon with 25% more range" (#2535)
original string from original str - Bomb Truck becomes a biowar weapon
Which one to pick?

2024-12-11 07:49 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Commands special weapons. Creates Construction Dozers. Grants ability to deploy a Radar"
I did all of the loca changes in one file and then separated them by language on github because of your comment. Also I want too see which changes are approved, to make them for all languages

2024-12-11 07:51 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Nuke Cannons lob small tactical nukes great distances\n\nBuild at: War Factory" (#2535)
original string from original str - Nuke Cannons lob small tactical nukes great distances\n\nBuild at: War Factory\nRequires: Propaganda Center

2024-12-11 07:54 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Chinese-Occupied Jambul, Kazakhstan\nOperation: Righteous Fire"
fixed

2024-12-11 07:55 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Toggle displaying additional game props. Turn off for improved performance"
fixed

2024-12-11 07:59 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "gattling" to "gatling" (#2535)
fixed

2024-12-11 08:05 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Heavy lift transport\nCan upgrade with base defense structures and Napalm Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, ant
Fixed

2024-12-11 08:05 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "gattling" to "gatling" (#2535)
fixed

2024-12-11 08:11 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Nuke Bomber: &T" (#2535)
fixed

2024-12-11 08:12 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Super-sonic attack makes Aurora immune to enemy fire. After super-sonic attack, Aurora speed is reduced to 50%. Equipped with a Point Defense Las
fixed

2024-12-25 08:44 UTC, xezon reviewed
This change needs splitting. There are a multitude of string edits where all or multiple languages need to be touched. All of these need to be part of isolated changes.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Cannon: &C" (#2535)
"Gattling Cannon: &C" cannot be the original string. Several times in this file.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 11/12/2024 Changes US from "Carpet Bomb: &T" (#2535)
Remove this line and append `(#2535)` to comment above.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Cannon: &C" (#2535)
Remove this line and append `(#2535)` to comment above.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Build a Gattling Cannon on this tank" (#2535)
Remove this comment and append `(#2535)` to the `@feature` comment above.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 10/12/2024 Changes US from "+25% rate of fire for Red Guard, Tank Hunter and Battlemaster"(#2535)
Remove this line and append `(#2535)` to the comment above.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Commands special weapons. Creates Construction Dozers. Grants ability to deploy a Radar"
I suggest move this change out of this one, and all other changes that make substantial changes to a string across all languages. Otherwise it is very difficult to keep track of this across all languages.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Chinese-Occupied Zambul, Kazakhstan\nOperation: Righteous Fire"
Now here it is named "Zambul", but elsewhere it is named "Zhambyl"

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Show Units Behind Buildings"
I suggest edit this for all languages, not just English.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix xezon 01/09/2023 Fixes punctuation inconsistencies in ACADEMY, buddy, DIALOGEVENT, GENERIC, GUI, HELP, LOSE, MAP, MDGLA02, MDGLA03, MD_GLA05, QM, SCRIPT, TOOLTIP, WOL, SpecialThanx3
CREDITS

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Carpet Bomber"
I suggest make a separate change for this and cater to all languages. Originall all languages say "Bomb" instead of "Bomber".

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nPurchase the Sentry Done gun from the War Factory"
I suggest move this change to a separate change and fix it for all languages.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Stealth Bomber's Bunker Buster upgrade can kill garrisoned enemies"
This needs to be adjusted for all languages

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the Leaflet Drop to disable enemy units"
This needs to be adjusted for all languages.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nAvengers are support units that can neutralize missiles and attack aircraft"
Ideally this is adjusted for all languages.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nCombat Cycle can jump off of cliffs"
Cycles

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nWorkers can use Combat Cycle to travel quickly"
Cycles

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nSatellite Hack 2 temporarily reveals all that enemy units can see"
This also needs tweaking for the other languages.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse Combat Cycle to enter the USA base from another direction"
Cycles

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +
Excess line

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "+25% rate of fire for Mini-Gunner and Tank Hunter" (#2535)
Remove this line and append `(#2535)` to the comment above.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Heavy lift transport\nCan be equiped with supporting or offensive installations and Napalm Bombs\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
"base defense structures" is used because Bunker, Propaganda Tower and Gattling Cannon are 3 base defense structures of China. I think it is ok to keep that wording.

2024-12-25 08:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "While the GLA has no need for power, China and the USA eat it up like popcorn. Running on low power puts your production and defenses at a disadvantage. Make sure to build a Cold Fusion Reactor
Now looking at it again, the last sentence is now a duplicate to "Running on low power puts your production and defenses at a disadvantage".

I suggest change last sentence to "Without power you have no chance in this war", which resembles what the German text says.

2024-12-25 12:57 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Cannon: &C" (#2535)
fixed

2024-12-25 12:58 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 11/12/2024 Changes US from "Carpet Bomb: &T" (#2535)
fixed

2024-12-25 12:59 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Gattling Cannon: &C" (#2535)
fixed

2024-12-25 12:59 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 04/12/2024 Changes US from "Build a Gattling Cannon on this tank" (#2535)
fixed

2024-12-25 13:01 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Chinese-Occupied Zambul, Kazakhstan\nOperation: Righteous Fire"
fixed

2024-12-25 13:01 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Show Units Behind Buildings"
I will do it in separate file

2024-12-25 13:02 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix xezon 01/09/2023 Fixes punctuation inconsistencies in ACADEMY, buddy, DIALOGEVENT, GENERIC, GUI, HELP, LOSE, MAP, MDGLA02, MDGLA03, MD_GLA05, QM, SCRIPT, TOOLTIP, WOL, SpecialThanx3
fixed

2024-12-25 13:02 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Carpet Bomber"
I will do it in separate file

2024-12-25 13:03 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nPurchase the Sentry Done gun from the War Factory"
I will do it in separate file

2024-12-25 13:03 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Stealth Bomber's Bunker Buster upgrade can kill garrisoned enemies"
I will do it in separate file

2024-12-25 13:03 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the Leaflet Drop to disable enemy units"
I will do it in separate file

2024-12-25 13:03 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nAvengers are support units that can neutralize missiles and attack aircraft"
I will do it in separate file

2024-12-25 13:04 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nCombat Cycle can jump off of cliffs"
fixed

2024-12-25 13:04 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nWorkers can use Combat Cycle to travel quickly"
fixed

2024-12-25 13:04 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nSatellite Hack 2 temporarily reveals all that enemy units can see"
I will do it in separate file

2024-12-25 13:05 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse Combat Cycle to enter the USA base from another direction"
fixed

2024-12-25 13:05 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +
fixed

2024-12-25 13:05 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "+25% rate of fire for Mini-Gunner and Tank Hunter" (#2535)
fixed

2024-12-25 13:07 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "While the GLA has no need for power, China and the USA eat it up like popcorn. Running on low power puts your production and defenses at a disadvantage. Make sure to build a Cold Fusion Reactor
fixed

2024-12-25 13:08 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Heavy lift transport\nCan be equiped with supporting or offensive installations and Napalm Bombs\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
Fixed

2025-01-03 17:24 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: ""
This probably should not remove DE texts here.

2025-01-03 17:24 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "" (#2535)
There are a bunch of change comments without changes here.

2025-01-03 17:24 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Stealthed while moving\nEquipped with a Point Defense Laser\n\nStrong vs. base defenses\nWeak vs. rocket soldiers" (#2535)
Perhaps can simplify comment with `Changes first US sentence from "Stealthed while moving"`

Other than that, original text was different, because comment above does say that "enemy" was removed.

2025-01-03 18:03 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Heavy lift transport\nupgrades with base defense structures and Napalm Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. missile armed infantry,
Can remove this comment and append `(#2535)` to comment above.

2025-01-03 18:03 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Demolitions ability enables all units to detonate after death or at your command"
The other languages are still closer to what the original English said.

2025-01-03 18:03 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "TBD" (#2535)
This comment is wrong. Several times in this file.

2025-01-03 18:03 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "TBD"
This change touches DE and FR several times unexpectedly.

2025-01-03 18:03 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Heavy lift transport\nupgrades with base defense structures and Nuke Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. missile armed infantry, a
Can remove this comments and append `(#2535)` to comment above.

2025-01-03 18:03 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Heavy lift assault transport\nCan upgrade with Bunker and Napalm Bombs\n\nStrong vs. tanks, light vehicles\nWeak vs. missile armed infantry, anti-air defenses"
This was meant to say "rocket soldiers" for consistency.

2025-01-03 18:03 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "Heavy lift assault transport\nupgrades with base defense structures and Napalm Bomb\n\nStrong vs. tanks, light vehicles\nWeak vs. missile armed i
Remove this comment and append `(#2535)` to first comment above.

2025-01-03 18:03 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Heavy lift transport\nCan upgrade with base defense structures and Napalm Bombs\n\nStrong vs. tanks, light vehicles\nWeak vs. rocket soldiers, anti-air defenses"
Is this also changed to plural in the other languages? DE, FR already are plural.

2025-01-03 18:03 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -US: "WARNING:\nDr. Thrax has been known to use a Sneak Attack\nTunnel Network to surprise enemies"
I am not sure if removing "Tunnel Network" is better here. The other languages also mention tunnel networks. And technically the Sneak Attack is a Tunnel Network.

2025-01-03 18:03 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Nuke Carpet Bomber"
I do not understand the question.

2025-03-01 05:41 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Commands special weapons. Creates Construction Dozers. Grants ability to deploy a Radar"
Will do

2025-03-01 05:53 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Repairs vehicles and heals soldiers nearby. Cleans up radiation and toxins"
All fixed

2025-03-01 05:57 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "ADVANCED GRAPHICS SETTINGS"
Fixed

2025-03-01 06:00 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Show Units Behind Buildings"
fixed

2025-03-01 06:46 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Domination Honor\nPlayer has won over 10000 Skirmish games"
All such instances were made identical

2025-03-01 12:17 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Commands special weapons. Creates Construction Dozers. Grants ability to deploy a Radar"
fixed

2025-03-01 12:17 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Camouflaged while not moving. Spots hidden enemies\n\nStrong vs. infantry\nWeak vs. light vehicles, scouts"
fixed

2025-03-01 12:21 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Repairs vehicles and heals soldiers nearby. Cleans up radiation and toxins"
fixed

2025-03-01 12:24 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Nuclear Shells: &N"
fixed

2025-03-01 12:53 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the Leaflet Drop to disable enemy units"
fixed

2025-03-01 13:06 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Stealth Bomber's Bunker Buster upgrade can kill garrisoned enemies"
I need help with DE, FR, ES, IT, BP, PL lines. Other lines were fixed.

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "This Bomb Truck becomes a bioweapon and improves its explosion range by 25%"
```suggestion
US: "This Bomb Truck becomes a bioweapon and increases its explosion range by 25%"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "USA fence system. Laser-sensors alert when enemy troops move through the fence. Fence blocks enemy vehicle movement"
```suggestion
US: "USA fence system. Laser-sensors alert when enemy troops move through the fence. Fences block enemy vehicle movement"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Nuke Cannons lob small tactical nukes at great distances\n\nBuild at: War Factory"
```suggestion
US: "Nuke Cannons lob small tactical nukes over great distances\n\nBuild at: War Factory"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Creates a surprise ambush of Rebels anywhere\n\nRank 1: 4 Rebels\nRank 2: 6 Rebels\nRank 3: 10 Rebels\n\nDeploy from: Command Center"
Flows better with placement specificity.
```suggestion
US: "Creates a surprise ambush of Rebels anywhere on the map\n\nRank 1: 4 Rebels\nRank 2: 6 Rebels\nRank 3: 10 Rebels\n\nDeploy from: Command Center"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "You have created a pile of salvage. Whenever GLA vehicles destroy enemy vehicles, salvage is left behind. GLA vehicles can pick up salvage by moving over it. Salvage may be worth money or experi
Should we address the absence of SCUD Launchers, Toxin Tractors, Scorpions and Battle Buses?

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Higher resolution textures can slow down the game"
'Slow down' is a separable phrasal verb and these are thus unnecessary changes.

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Disable automatic detail adjustment (LOD). Turn off for improved performance"
Is placing an acronym without a corresponding full form a helpful addition, or could it potentially introduce confusion and leave users wondering what 'LOD' means?

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Toggle On/Off - Turn Off to improve performance"
```suggestion
US: "Toggle On/Off - Turn off to improve performance"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "One or more players have been disconnected from the game. If you choose to vote a person out of the game then click the VOTE button next to the respective player. When the timer counts down to 0
Standardise language.
```suggestion
US: "One or more players have been disconnected from the game. If you choose to vote a player out of the game then click the VOTE button next to the respective player. When the timer counts down to 0 that player will be automatically removed from the game and the battle will continue"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "It is possible that the person is attempting to reconnect so you may choose to wait until this player's timer has elapsed. When the timer counts down to 0 that person will be automatically remov
```suggestion
US: "It is possible that the player is attempting to reconnect so you may choose to wait until this player's timer has elapsed. When the timer counts down to 0 that player will be automatically removed from the game and the battle will continue"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Right mouse button initiates unit action on battlefield (attack, move, etc.)"
```suggestion
US: "The right mouse button initiates unit action on the battlefield (attack, move, etc.)"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Domination Honor\nPlayer has won over 10000 Skirmish games"
You can't use the same separator for all languages. See: [Decimal Separator](https://en.wikipedia.org/wiki/Decimal_separator)

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 06/12/2024 Changes US from "USA" to "US" (#2535)
I see no change.

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Select Aircraft Carrier"
Does the function only ever select one aircraft carrier? Or does it select many if multiple are present? If the latter, it'd be better to make the plural optional.
```suggestion
US: "Select Aircraft Carrier(s)"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Avenger laser can 'paint' enemy targets\nAllied units attack 'painted' targets with increased fire rate"
```suggestion
US: "HINT:\nThe Avenger's laser can 'paint' enemy targets\nAllied units attack 'painted' targets with increased fire rate"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Avenger laser can 'paint' enemy targets\nAllied units attack 'painted' targets with increased fire rate"
Maybe replace `'paint'` with `focus`, which is a more _accurate_ term (see what I did there?) that negates the need for quotes?
```suggestion
US: "HINT:\nThe Avenger's laser can focus enemy targets\nAllied units attack focused targets with increased fire rate"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Avenger laser can 'paint' enemy targets\nAllied units attack 'painted' targets with increased fire rate"
Alternatively `mark`, inspired by the German translation.
```suggestion
US: "HINT:\nThe Avenger's laser can mark enemy targets\nAllied units attack marked targets with increased fire rate"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Avenger laser can 'paint' enemy targets\nAllied units attack 'painted' targets with increased fire rate"
Also worth considering whether to specify `ground` targets for this ability.

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Stealth Bomber's Bunker Buster upgrade can kill garrisoned enemies"
Is this necessary? Unsure about this one as Bunker Busters don't necessarily kill enemy units. I suppose the 'can' still makes it valid, but the original wording doesn't need the 'can' anyway.

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nAdvanced Nuclear Power Plants generate more power than normal Nuclear Plants"
Better to align the hint text with the object names. Standard might be a better fit than normal.
```suggestion
US: "HINT:\nAdvanced Nuclear Reactors generate more power than standard Nuclear Reactors"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the Frenzy General's Power to temporarily increase the firepower and armor of your units"
This change makes it sound like the text is referring to a Frenzy General.
```suggestion
US: "HINT:\nUse the Frenzy Generals' Power to temporarily increase the firepower and armor of your units"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nGLA General's Powers are available at the GLA Command Center"
```suggestion
US: "HINT:\nGLA Generals' Powers are available at the GLA Command Center"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Temporarily increases damage of targeted units\n\nRank 1: +10% damage for 10 seconds\nRank 2: +20% damage for 20 seconds\nRank 3: +30% damage for 30 seconds\n\nDeploy from: Command Center"
'Damage' is somewhat ambiguous. Align with terminology used in the Frenzy hints and elsewhere in the game.
```suggestion
US: "Temporarily increases the firepower of targeted units\n\nRank 1: +10% firepower for 10 seconds\nRank 2: +20% firepower for 20 seconds\nRank 3: +30% firepower for 30 seconds\n\nDeploy from: Command Center"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "While the GLA has no need for power, China and the USA eat it up like popcorn. Running on low power puts your production and defenses at a disadvantage. Make sure to build a Cold Fusion Reactor
Is `Without power you have no chance in this war` really necessary?

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "General, make sure you're building plenty of Workers, Supply Trucks or Chinooks to keep your income flowing. You can make extra gatherers by clicking on the resource gatherer's picture in the Su
```suggestion
US: "General, make sure you're building plenty of Workers, Supply Trucks or Chinooks to keep your income flowing. You can purchase extra gatherers by clicking on the resource gatherer's picture in the Supply Center or Stash. Don't be shy about maximizing your resource potential"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Garrisoned buildings can be tough to handle - unless you know some tricks. Upgrade your US Rangers with Flash Bangs, build GLA Toxin Tractors or Chinese Dragon Tanks to quickly clear out these s
```suggestion
US: "Garrisoned buildings can be tough to handle - unless you know some tricks. Upgrade your US Rangers with Flash Bangs, or build GLA Toxin Tractors or Chinese Dragon Tanks to quickly clear out these strong points. The USA can also upgrade to the Bunker Buster to even clear out Tunnel Networks!"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Supplies are the name of the game, General. They can be gathered at Supply Docks littered around the battlefield. While one dock may be enough early on it's usually best to branch out and find a
```suggestion
US: "Supplies are the name of the game, General. They can be gathered at Supply Docks littered around the battlefield. While one dock may be enough early on, it's usually best to branch out and find a few more during a mission. You'll need to build a Supply Center or Stash close to the Supply Dock to ensure efficient collection"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Some structures can be upgraded to camouflage, like the GLA Tunnel Network or Stinger Sites. These will be invisible to the enemy until it's too late. Surprise!"
```suggestion
US: "Some structures can be upgraded with camouflage, like the GLA Tunnel Network or Stinger Site. These will be invisible to the enemy until it's too late. Surprise!"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "*Warning: Particle Cannon activation detected"
Better to match audio?
```suggestion
US: "*Warning: A Particle Cannon has been activated"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "*Well done General. You have reached a higher rank"
```suggestion
US: "*Well done, General. You have reached a higher rank"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "*Be on alert, A Daisy Cutter bomb may be approaching"
```suggestion
US: "*Be on alert, a Daisy Cutter bomb may be approaching"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "*Be on alert, An EMP Pulse bomb may be approaching"
```suggestion
US: "*Be on alert, an EMP Pulse bomb may be approaching"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "*Be on alert, A Fuel-Air bomb may be approaching"
```suggestion
US: "*Be on alert, a Fuel-Air bomb may be approaching"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "*Congratulations General. You have been promoted"
```suggestion
US: "*Congratulations, General. You have been promoted"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "*Warning: GPS Scrambler Detected"
Match audio.
```suggestion
US: "*Warning: GPS Scrambler activated"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Advanced Demo Trap\nDemolitions Ability\nTerrorists do more damage\nStarts with Booby Trap\nCombat Cycle begin with Terrorist\nNo camouflaged units\nBomb Trucks cost less"
```suggestion
US: "Advanced Demo Trap\nDemolitions Ability\nTerrorists do more damage\nStarts with Booby Trap\nCombat Cycles begin with a Terrorist\nNo camouflaged units\nBomb Trucks cost less"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +
These are all unnecessary?

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Game has disappeared"
```suggestion
US: "The game has disappeared"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Click to begin QuickMatch. QuickMatch will attempt to automatically match you with a player who has the closest skill level and preferences"
```suggestion
US: "Click to begin QuickMatch. QuickMatch will attempt to automatically match you to a player with the closest skill level and preferences"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Laser-guided Missiles"
The standard seems to be that hyphenated compound words are both capitalised in titles.
```suggestion
US: "Laser-Guided Missiles"
```

2025-03-01 13:09 UTC, Stubbjax commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nSatellite Hack 2 temporarily reveals all that enemy units can see"
Better to align with names / other instances.
```suggestion
US: "HINT:\nSatellite Hack II temporarily reveals all that enemy units can see"
```

2025-03-01 13:27 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nUse the Frenzy General's Power to increase the firepower and armor of your units for a limited time"
I need help with DE, FR, ES, IT, KO, BP, PL lines. Other lines were fixed.

2025-03-01 13:28 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Where are my troops? Please let me go, OK? Don't hurt me!"
Yes. Its now a part of TBD line fixes branch

2025-03-01 13:28 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "We have nice uniforms... come and see us... you will like it.\nOr not"
Yes. Its now a part of TBD line fixes branch

2025-03-01 13:30 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Nuke Carpet Bomber"
I should leave it as a Nuke Bomber, right?

2025-03-01 20:16 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Click to begin QuickMatch. QuickMatch will attempt to automatically match you with a player who has the closest skill level and preferences"
Agreed with `to`

2025-03-01 20:31 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "- Call in Carpet Bombers and destroy the GLA"
```suggestion
US: "- Call in Carpet Bombers to assist with destroying the GLA bases"
```

Might be more descriptive. This appears in the mission loading screen. The vanilla text implies that you have to use the bombers.

2025-03-01 20:32 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Loo"
In the US these are called Out Houses. `Loo` is UK English.

2025-03-01 20:38 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "You have created a pile of salvage. Whenever GLA vehicles destroy enemy vehicles, salvage is left behind. GLA vehicles can pick up salvage by moving over it. Salvage may be worth money or experi
```suggestion
US: "You have created a pile of salvage. Salvage is left behind whenever GLA vehicles destroy an enemy vehicle. GLA vehicles pick up salvage by moving over it. Salvage may grant weapon upgrades, money, or experience. Technicals, Quad Cannons, and Marauders will upgrade their weapons with salvage. "
```

- Switch from passive to active voice.
- Make it clearer what salvage doesn

2025-03-01 20:47 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Higher resolution textures can slow down the game"
`may negatively affect performance` might be more accurate.

2025-03-01 20:53 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Disable automatic detail adjustment (LOD). Turn off for improved performance"
Agreed, maybe

```suggestion
US: "Disable automatic level-of-detail adjustment. Turn off for improved performance"
```

2025-03-01 20:56 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "One or more players have been disconnected from the game. If you choose to vote a person out of the game then click the VOTE button next to the respective player. When the timer counts down to 0
Also more accurate if I ever get a machine learning model to play the game.

2025-03-01 21:02 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "It is possible that the person is attempting to reconnect so you may choose to wait until this player's timer has elapsed. When the timer counts down to 0 that person will be automatically remov
```suggestion
US: "It is possible that the player is attempting to reconnect; you may choose to wait until the reconnect timer has elapsed. The player will be automatically removed from the game if the timer counts down to 0, and the game will continue without them."
```

2025-03-01 21:03 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Right mouse button initiates unit action on battlefield (attack, move, etc.)"
`actions`

2025-03-01 21:05 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "Select Aircraft Carrier"
There's only one mission with this button and it only has one carrier.

2025-03-01 21:07 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nPurchase the Sentry Done gun from the War Factory"
```suggestion
US: "HINT:\nPurchase the Sentry Drone machine-gun upgrade from the War Factory"
```

2025-03-01 21:10 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Avenger laser can 'paint' enemy targets\nAllied units attack 'painted' targets with increased fire rate"
`Paint` is accurate to US military terminology. IRL military uses lasers to paint targets

2025-03-01 21:12 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nAvengers are support units that can neutralize missiles and attack aircraft"
```suggestion
US: "HINT:\nAvengers are support units that neutralize missiles, attack aircraft, and laser-designate ground targets"
```

2025-03-01 21:14 UTC, alexlambson commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nThe Stealth Bomber's Bunker Buster upgrade can kill garrisoned enemies"
```suggestion
US: "HINT:\nThe Stealth Bomber's Bunker Buster upgrade can kill garrisoned infantry, while minimizing damage to the structure"
```

Maybe too wordy, but more descriptive.

2025-03-04 10:30 UTC, dmgreeny commented
Thank you for checking these changes. @alexlambson @Stubbjax 
Please also check English lines here:
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2571

2025-03-04 21:56 UTC, TheMyFish requested changes

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "Bombardeiro de carpete"
The previous translation was much better.
BP: "Bombardeio de Saturação"

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "Bombardeiro de carpete: &G"
The previous translation was much better. I understand that the translation is like a carpet, but the phrase doesn't seem to mean what's going to happen, and the translation is much more tactical.
BP: "Bombardeio de Saturação: &G"

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "Bombardeiro de carpete: &G"
Same logic phrase.
BP: "Bombardeio de Saturação: &G"

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "Bombardeiro de carpete"
The earlier translation was better.
BP: "Bombardeio de Saturação"

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  BP: "O Caminhão Bomba se torna uma Arma Biológica com 25% a mais de alcance."
I'm emphasising that the blast radius has increased by 25%
BP: "Este Caminhão-Bomba torna-se uma arma biológica e aumenta o seu alcance de explosão em 25%”

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "Controla armas especiais. Cria Construtores. Implanta radar."
I understand about using the word builders, but since we're talking about the USA, shouldn't it be dozers? instead of builders.

BP: "Comanda armas especiais. Cria Tratores de Construção. Implanta Radar."

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "- Call in Carpet Bombers and destroy the GLA"
I agree, if this is a campaign mission, it should be as descriptive as possible.

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "- Chame os Carpet Bombers e destrua o GLA."
Using the context that this is a USA campaign, it should be more descriptive.
BP: "Solicitar bombardeiros de saturação para ajudar a destruir as bases do GLA."

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "DICA:\nCarpet Bombers já estão disponíveis."
the previous translation is better
BP: "DICA:\nBombardeio de Saturação já estão disponíveis."

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "Bombardeiro de carpete"
Same logic phrase
BP: "Bombardeiro de Saturação"

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "Conchas nucleares: &N"
I understand that this must be an upgrade from Nuke Cannon where it has the option of nuke shells.
The translation shells is not good, I suggest changing it to nuclear projectiles.

BP: "Projéteis Nucleares: &N"

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "DICA:\nUse o Leaflet Drop para desabilitar unidades inimigas."
BP: "DICA: \nUse o Lançamento de Panfletos para desativar a infantaria inimiga."

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "DICA:\nCapture o posto de espionagem para contatar os Bombardeiro de carpete."
"DICA: Capture o posto de espionagem para chamar bombardeiros de saturação."

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "RECEBENDO TRANSMISSÃO:\nOs Bombardeiro de carpete estão prontos."
BP: "RECEBENDO TRANSMISSÃO:\nOs Bombardeiro Saturação estão prontos."

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "*General, I've made contact with one of our spy outposts. They are under GLA attack. If we can rescue them, I can patch into their system and we will be able to call in Carpet bombers"
BP:  "General, entrei em contato com um dos nossos postos de espionagem. Eles estão sob ataque do GLA. Se conseguirmos resgatá-los, posso conectar nosso sistema ao deles e seremos capazes de chamar bombardeiros de saturação."

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  BP: "*General, if you can secure that spy outpost, it will allow you to direct carpet bombing runs on the GLA forces"
BP: "*"General, se você conseguir assegurar aquele posto de espionagem, isso permitirá que você direcione bombardeios de saturação sobre as forças do GLA.""

2025-03-04 21:56 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  BP: "*Our new Carpet Bomber plane drops a series of bombs along a targeted path, decimating all enemy forces"
BP: "*Nosso novo bombardeiro de saturação lança uma série de bombas ao longo de um caminho alvo, dizimando todas as forças inimigas."

2025-03-05 23:34 UTC, CrabHead requested changes
Polish translation check done as requested. A few things were wrong but most was alright.

There is this matter with the Carpet Bomb, or rather Carpet Bomber now. 
While Carpet Bomber translates to Bombowiec dywanowy. Translation is correct, but it's one of those phrases in Polish that make sense in English and are translatable in Polish but they just don't make sense, because no one uses them (and it just sounds strange). Everyone uses Nalot dywanowy (carpet bombing) and the Polish translation uses it as well.

My question is, could the translation be reverted back to the OG Polish translation? Or is it needed to have translations consistent with English?

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "Zwiększa prędkość Imperatora Overlorda i Mistrza Bitwy o 25%."
Change "Imperatora Overlorda" to "Cesarza" and "Mistrza Bitwy" to "Pancernej Pięści"

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "Steruje uzbrojeniem specjalnym. Buduje buldożery. Rozmieszcza Radar."
Change from "Romieszcza" to "Rozstawia"

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "Naprawia pojazdy i leczy pobliskich żołnierzy. Oczyszcza promieniowanie i toksyny."
Change from "Oczyszcza promieniowanie i toksyny." to "Oczyszcza z promieniowania i toksyn."

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "RADA:\nDywany Carpet Bombers są już dostępne."
Change from "Dywany Carpet Bombers" to "Bombowce dywanowe"

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "RADA:\nDziałko robota strażniczego można zakupić w War Factory."
Change from "War Factory" to "Fabryce wojennej"

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "RADA:\nAvengers to jednostki wsparcia, które potrafią neutralizować rakiety i samoloty szturmowe."
Change from "Avengers" to "Mściciele". Rest is fine

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "RADA:\nUżyj Ulotki, aby unieszkodliwić jednostki wroga."
Change from "Ulotki," to "Zrzutu Ulotek,"

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "RADA:\nSatellite Hack 2 okresowo ujawnia wszystko, co widzą wrogie jednostki."
Change from "Satellite Hack 2" to "Łącze hakerskie 2"

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "RADA:\nUmiejętność „Detonacje” umożliwia wszystkim jednostkom detonację po śmierci lub na twój rozkaz."
Change from "Detonacje" to "Detonuj" (forgot what's the actual polish translation for this ability, but this is probably it)

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "Zwiększa prędkość Imperatora Overlorda i Mistrza Bitwy o 25%."
Change from "Imperatora Overlorda" to "Cesarza, "Mistrza Bitwy" to "Pancernej Pięści"

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "Ciężki transport ładunków\nMożna ulepszać za pomocą bazowych struktur obronnych i bomb napalmowych\n\nSilny przeciwko czołgom, lekkim pojazdom\nSłaby przeciwko żołnierzom rakietowym, obronie prz
Change from "Ciężki transport ładunków" back to "Ciężki transportowiec". Same meaning but the OG translation makes more sense.

Change from "Można ulepszać za pomocą bazowych struktur obronnych i bomb napalmowych" to "Można go ulepszyć w systemy obronne i bombę napalmową."

Change from "żołnierzom rakietowym" back to "piechocie rakietowej." (without the double piechocie)

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "Zwiększa prędkość Imperatora Overlorda i Mistrza Bitwy o 25%."
change from "Imperatora Overlorda" to "Cesarza" and "Mistrza Bitwy" to "Pancernej Pięści"

2025-03-05 23:34 UTC, CrabHead commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +PL: "Ukryty\nWyposażony w laser do obrony punktowej\n\nSilny przeciwko obronie bazy\nSłaby przeciwko żołnierzom rakietowym"
Change from 'Ukryty' to 'Zamaskowany'

Change from "żołnierzom rakietowym" to "piechocie rakietowej"

2025-03-06 10:38 UTC, dmgreeny commented
All changes applied. Please check again

2025-03-06 11:33 UTC, YarPik2 requested changes

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  UK: "Ваш серійний номер уже використовується"
"Ваш серійний номер вже використовується"

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +UK: "+25% до швидкості пересування Імператора, Владики та Майстра бою"
"+25% до швидкості пересування Імператора, Повелителя та Майстра бою"

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +UK: "Закамуфльований, поки не рухається. Виявляє прихованих ворогів\n\nСильні проти піхоти\nСлабкі та легкі машини, розвідники"
"Закамуфльований, поки не рухається. Виявляє прихованих ворогів\n\nСильний проти піхоти\nСлабкий проти легкої техніки, розвідників"

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +UK: "Показати Підрозділи за будівлями"
"Показувати Підрозділи за будівлями"

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +UK: "ПІДКАЗКА:\nВикористовуйте листівку, щоб вивести з ладу ворожих одиниць"
"ПІДКАЗКА:\nВикористовуйте листівки, щоб вивести з ладу ворожі одиниці" or "ПІДКАЗКА:\nВикористовуйте листівки, для виведення з ладу ворожих одиниць"

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +UK: "ПІДКАЗКА:\nВзлом Спутника 2 періодично показує все, що видять вражеские войска"
"ПІДКАЗКА:\nЗлам Спутника 2 періодично показує все, що бачать ворожі війська"

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +UK: "+25% до швидкості пересування Імператора, Владики та Майстра бою"
UK: "+25% до швидкості пересування Імператора, Повелителя та Майстра бою"

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +UK: "Важкий транспортний вертоліт\nМожуть бути встановлені захисні споруди та Бомби з напалмом\n\nСильна проти танків та легкої піхоти\nСлаба проти піхоти озброєної ракетами та систем ППО бази"
"Важкий транспортний вертоліт\nМожуть бути встановлені захисні споруди та Бомби з напалмом\n\nСильний проти танків та легкої піхоти\nСлабкий проти піхоти озброєної ракетами та систем ППО бази"

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +UK: "*General, I've made contact with one of our spy outposts. They are under GLA attack. If we can rescue them, I can patch into their system and we will be able to call in Carpet bombers"
"*Генерал, я зв’язався з одним із наших шпигунських постів. Вони під атакою ГВА. Якщо ми їх врятуємо, я зможу підключитися до їхньої системи, і ми зможемо викликати Килимових бомбардувальників"

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +UK: "+25% до швидкості пересування Імператора, Владики та Майстра бою"
"+25% до швидкості пересування Імператора, Повелителя та Майстра бою"

2025-03-06 11:33 UTC, YarPik2 commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +UK: "Невидимий\nОбладнаний Захисним лазером\n\nСилєн проти оборони баз\nСлаб проти винищувачів"
"Невидимий\nОбладнаний Захисним лазером\n\nСильний проти оборони баз\nСлабкий проти винищувачів"

2025-03-06 18:00 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Tu núm de serie ya está en uso."
I don't know why they shorten "número" (number), the entire word should fit there. Should be: "Tu número de serie ya está en uso."

2025-03-06 18:02 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cañón Gattling: &C"
In Spanish we say "Gatling" with only one "t", remove the extra one like on the other languages.

2025-03-06 18:02 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Tanque Gattling: &G"
Same as above.

2025-03-06 18:02 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Tanque Gattling: &A"
Same as above.

2025-03-06 18:03 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cañón Gattling: &A"
Same as above.

2025-03-06 18:05 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Misiles Láser América"
According to the changes made to the US string, the Spanish string should now be: "Misiles guiados por láser"

2025-03-06 18:05 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cañón Gattling Overlord"
Remove the extra "t" in "Gattling"

2025-03-06 18:05 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Tanque Gattling"
Same as above.

2025-03-06 18:06 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cañón Gattling"
Same as above.

2025-03-06 18:07 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Starlifter2"
Missing space between "r" and "2" in Spanish string.

2025-03-06 18:07 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Construye un Cañón Gattling en este Overlord."
Remove the extra "t" in "Gattling".

2025-03-06 18:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "El camión bomba se convierte en un arma biológica con un 25 % más de alcance."
To reflect US strings changes, the Spanish string should be: "El camión bomba añade bioquímicos a sus explosivos mejorando su alcance de explosión en un 25 %"

2025-03-06 18:15 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Ordena a los Rangers que caigan sobre el objetivo enemigo. Se usa para matar a todos los soldados enemigos guarnecidos en edificios."
To reflect US strings changes, the Spanish string should be: "Ordena a los Rangers que caigan sobre los objetivos enemigos. Se usa para matar a todos los soldados enemigos guarnecidos en edificios."

2025-03-06 18:20 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Ordena armas especiales. Crea Excavadoras."
To reflect US string changes, Spanish string now should be: "Ordena armas especiales. Crea Excavadoras. Pueden desplegar un radar."

2025-03-06 18:21 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Camuflado mientras no se mueve o dispara. Detecta enemigos ocultos.\n\nPotente contra infantería\nDébil contra vehículos ligeros, exploradores"
Remove "o dispara" to reflect US string changes.

2025-03-06 18:22 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cura soldados. Limpia radiaciones y toxinas."
To reflect US string changes, ES string should now be: "Repara vehículos y cura soldados cercanos. Limpia radiaciones y toxinas."

2025-03-06 18:23 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Crea una tormenta de fuego en grandes grupos.\n\nPotente contra tanques, vehículos ligeros\nDébil contra infantería con misiles, defensas antiaéreas"
To reflect US string changes, ES string should now be: "Crea una tormenta de fuego atacando en grupo.\n\nPotente contra tanques, vehículos ligeros\nDébil contra infantería con misiles, defensas antiaéreas"

2025-03-06 18:25 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Crea una tormenta de fuego en grandes grupos.\n\nPotente contra defensas de base, infantería\nDébil contra tanques, aviación"
To reflect US string changes, ES string should now be: "Crea una tormenta de fuego disparando en grupo.\n\nPotente contra defensas de base, infantería\nDébil contra tanques, aviación"

2025-03-06 18:27 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Transporte. Viene con 8 de la Guardia Roja. Detecta unidades.\n\nPotente contra infantería, edificios\nDébil contra tanques, aviación"
To reflect US string changes, ES string should now be: "Transporte. Viene con 8 guardias rojos. Detecta unidades.\n\nPotente contra infantería, edificios\nDébil contra tanques, aviación"

2025-03-07 00:50 UTC, TheMyFish commented
> Polish translation check done as requested. A few things were wrong but most was alright.
> 
> There is this matter with the Carpet Bomb, or rather Carpet Bomber now. While Carpet Bomber translates to Bombowiec dywanowy. Translation is correct, but it's one of those phrases in Polish that make sense in English and are translatable in Polish but they just don't make sense, because no one uses them (and it just sounds strange). Everyone uses Nalot dywanowy (carpet bombing) and the Polish translation uses it as well.
> 
> My question is, could the translation be reverted back to the OG Polish translation? Or is it needed to have translations consistent with English?  @CrabHead 

I think translations have to take the meaning of the sentence as their main reference in English but adopt it in the style of the native language we're translating. Just like the example in Brazilian Portuguese. The translation of ‘Carpet Bomber’ is ‘Bombardeiro de Tapete’, but that doesn't sound interesting and doesn't make sense to us Brazilians. Here we use it as "Saturation Bomber’ aka "Bombardeiro de Saturação"

2025-03-07 00:59 UTC, DevGeniusCode commented
> My question is, could the translation be reverted back to the OG Polish translation? Or is it needed to have translations consistent with English?
Maybe we can see and use with the wikipedia how the entry is translated across different languages.

![image](https://github.com/user-attachments/assets/d5ecaa2a-2e44-4c41-8b72-2395906b94ad)

2025-03-07 03:09 UTC, TheMyFish requested changes
Most of the changes are legal. I've also suggested some new translations and questions.

2025-03-07 03:09 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  BP: "DICA:\nCompre a arma do Drone Sentinela na War Factory."
BP: "DICA:\nCompre a arma do Drone Sentinela na Fábrica de Guerra."

2025-03-07 03:09 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +BP: "DICA:\nUse o Lançamento de Panfletos para desativar a infantaria inimiga."
Thinking about this translation, I think I made the mistake of mentioning only infantry because this USA skill paralyses any enemy unit not just infantry. It would be good to mention this for all translations as well.
Source; https://cnc.fandom.com/wiki/Leaflet_drop

BP: "DICA:\nUse o Lançamento de Panfletos para paralisar unidades inimigas."

2025-03-07 03:09 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  BP: "DICA:\nO Satellite Hack 2 revela intermitentemente tudo o que as unidades inimigas podem ver."
"DICA:\nO Satélite Hack 2 revela intermitentemente tudo o que as unidades inimigas podem ver."

2025-03-07 03:09 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  BP: "Helix\nPostos Avançados de Escuta\nMinas de Nêutron\nAtaque Enfurecido\nCentro de Internet\nBombardeiro de carpete\nTanque ECM"
BP: "Helix\nPostos Avançados de Escuta\nMinas de Nêutron\nAtaque Enfurecido\nCentro de Internet\nBombardeiro de Saturação\nTanque ECM"

2025-03-07 03:09 UTC, TheMyFish commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  BP: "Furtivo\nEquipado com um Laser de Defesa de Ponto\n\nForte vs. defesas de base\nFraco vs. soldados de foguete"
Respecting the logic of previous sentences when you mention the word vs
BP: "Furtivo\nEquipado com um Laser de Defesa de Ponto\n\n Forte contra defesas de base\nFraco contra soldados de foguete"

2025-03-09 10:17 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +US: "HINT:\nAvengers are support units that can neutralize missiles and attack aircraft"
Careful with long mission string, they need to be line breaked at around 80 characters (until we have a code solution for it)

2025-03-12 17:14 UTC, ElTioRata requested changes

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Selecciona tu Proveedor de audio."
Should be "Selecciona tu dispositivo de audio" now.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 3 escaramuzas seguidas.\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 10 escaramuzas seguidas.\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Bombardero de alfombra"
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Tu núm de serie ya está en uso."
I don't know why número (number) is abbreviated here. The whole word should fit perfectly.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Tu núm de serie no es válido."
Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cañón Gattling: &C"
Remove the extra "t".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Tanque Gattling: &G"
Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Tanque Gattling: &A"
Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cañón Gattling: &A"
Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cañón Gattling: &A"
Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Bombardero de alfombra: &T"
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Bombardero de alfombra: &T"
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Misiles Láser América"
Should be now "Misiles guiados por láser"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cañón Gattling Overlord"
Remove the extra "t".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Bombardero de alfombra"
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Tanque Gattling"
Remove the extra "t".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cañón Gattling"
Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cubo de basura"
Should be now "Contenedor de basura" if it is a container indeed.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Zhambul, Kazajstán\nLos chinos controlan el centro de población civil..."
Should be "Zhambyl" instead of "Zhambul" to reflect US string changes.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Construye un Cañón Gattling en este Overlord."
Remove the extra "t".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Construye un Cañón Gattling en este tanque."
Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "+25% de cadencia de fuego para Guardia Roja, cazatanques y Battlemaster."
Should be now "+25% de cadencia de fuego para guardias rojos, cazatanques y Battlemasters."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "+25% de daños para todas las armas Gattling."
Remove the extra "t".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Aumenta la velocidad del Emperador Overlord y del Maestro de batalla en un 25 %."
Should be now: "Aumenta la velocidad del Emperor Overlord y Battlemaster en un 25%."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "El camión bomba se convierte en un arma biológica con un 25 % más de alcance."
Should be now "El camión bomba se convierte en un arma biológica y aumenta su alcance de explosión en un 25%"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Ordena a los Rangers que caigan sobre el objetivo enemigo. Se usa para matar a todos los soldados enemigos guarnecidos en edificios."
Should be now "sobre los objetivos enemigos." instead of "sobre el objetivo enemigo."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Ordena armas especiales. Crea Excavadoras. Despliega radar. Despliega radar."
Remove the extra "Despliega radar."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Usa un ataque guiado por láser con misiles de fuego rápido.\n\nPotente contra tanques, aviación\nDébil contra infantería"
Replace "Potente contra tanques, aviación" with "Eficaz contra tanques y aviación".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Camuflado sin moverse. Detecta enemigos ocultos\n\nFuerte contra infantería\nDébil contra vehículos ligeros y exploradores"
Replace "Camuflado sin moverse." with "Camuflado mientras no se mueve."
Replace "Fuerte contra infantería" with "Eficaz contra infantería".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Repara vehículos y cura a los soldados cercanos. Limpia la radiación y las toxinas."
Could be shorter. Replace with "Repara vehículos y cura soldados cercanos. Limpia radiación y toxinas."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Transporte. Viene con 8 de la Guardia Roja. Detecta unidades.\n\nPotente contra infantería, edificios\nDébil contra tanques, aviación"
Replace "Potente" with "Eficaz".
Replace "tanques, aviación" with "tanques y aviación".
Replace "Viene con 8 de la Guardia Roja." with "Viene con 8 guardias rojos."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Te permite crear una emboscada sorpresa de rebeldes en cualquier parte.\n\nRango 1: 4 rebeldes\nRango 2: 8 rebeldes\nRango 3: 16 rebeldes\n\nDespliegue desde: Centro de mando"
Add "del mapa" after "cualquier parte" to reflect US strings changes.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Te permite crear una emboscada sorpresa de rebeldes en cualquier parte.\n\nRango 1: 4 rebeldes\nRango 2: 6 rebeldes\nRango 3: 10 rebeldes\n\nDespliegue desde: Centro de mando"
Same as above (although at the time of this comment, the US string hasn't been changed yet).

Also replace "Te permite crear" for "Crea".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Llama a los matadores y destruye el GLA"
To reflect suggested changes, should be "Solicita bombardeo a nivel para asistir en la destrucción de bases del GLA"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Zhambul, territorio ocupado por China, Kazajstán\nOperación: Fuego Justificado"
Should be "Zhambyl" instead of "Zhambul".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "PISTA:\nBombardero de alfombra disponibles."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Has creado una pila de objetos salvados. Siempre que los vehículos de GLA destruyan vehículos enemigos, los dejarán atrás. Los vehículos de GLA pueden cogerlos, pasando por encima. Los podrás ca
To reflect suggested changes, it should now be:
"Has creado una pila de objetos salvados. Se dejarán atrás siempre que los vehículos de GLA destruyan un vehículo enemigo. Los vehículos de GLA pueden cogerlos, pasando por encima. Los podrás cambiar por mejoras de armas, dinero o experiencia. Las Camionetas, Cañones Quad y Marauders mejorarán sus armas con objetos salvados."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 25 escaramuzas seguidas.\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Zambul"
Should be "Zhambyl" now.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "CONFIGURACIÓN GRÁFICA AVANZADA"
While this is _mostly_ correct, it's more common to be localized as "AJUSTES DE GRÁFICOS AVANZADOS".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Máyor número de partículas puede ralentizar el juego."
To reflect suggested changes, should be "Los recuentos de partículas elevados pueden afectar negativamente el rendimiento."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Desactivar ajuste de detalle automático. Desactivar para mejorar el rendimiento."
To reflect suggested changes, should be: "Desactivar ajuste de nivel de detalle automático. Desactivar para mejorar el rendimiento"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Activar Sí/No - No para mejorar el rendimiento."
Should be "Activar o desactivar - Desactivar para mejorar el rendimiento"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Uno o más jugadores han sido desconectados de la partida. Si eliges expulsar a una persona del juego, haz click sobre el botón Votar asignado al jugador. Cuando la cuenta atrás llegue a cero, es
To reflect suggested changes, should be:
"a un jugador" instead of "a una persona"
"ese jugador será expulsado" instead of "esa persona será expulsada"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Es posible que algún jugador este intentando reconectar, así que puedes elegir esperar hasta que el tiempo s de este jugador concluya. Cuando el contador llegue a 0, esa persona será desconecta
To reflect suggested changes, it should be;

"Es posible que un jugador esté intentando reconectar, puedes elegir esperar hasta que el tiempo de reconexión concluya. Cuando el contador llegue a 0, el jugador será desconectado de la partida y continuará sin él."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "El botón derecho del ratón inicia una acción en el campo de batalla (ataques, movimientos, etc.)"
To reflect suggested changes, it should be "inicia acciones".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 100 escaramuzas seguidas.\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 500 escaramuzas seguidas.\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 1,000 escaramuzas seguidas."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 3 partidas online seguidas.\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change. Also, "online" should be replaced with "en línea".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 10 partidas online seguidas.\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change. Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 25 partidas online seguidas.\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change. Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 100 partidas online seguidas.\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change. Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 500 partidas online seguidas.\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change. Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nEl jugador ha ganado 1,000 partidas online seguidas."
Revert change. Same as above.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (dominación)\nel jugador ha ganado más de 100 escaramuzas\nSe gana una medalla por 100, 500, 1,000 y 10,000 victorias en total."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (dominación)\nel jugador ha ganado más de 500 escaramuzas\nSe gana una medalla por 100, 500, 1,000 y 10,000 victorias en total."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (dominación)\nel jugador ha ganado más de 1,000 escaramuzas\nSe gana una medalla por 100, 500, 1,000 y 10,000 victorias en total."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (dominación)\nEl jugador ha ganado más de 10,000 escaramuzas."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (dominación)\nel jugador ha ganado más de 100 partidas online\nSe gana una medalla por 100, 500, 1,000 y 10,000 victorias en total."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (dominación)\nel jugador ha ganado más de 500 partidas online\nSe gana una medalla por 100, 500, 1,000 y 10,000 victorias en total."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (dominación)\nel jugador ha ganado más de 1,000 partidas online\nSe gana una medalla por 100, 500, 1,000 y 10,000 victorias en total."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (dominación)\nEl jugador ha ganado más de 10,000 partidas online."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (racha)\nSe gana medalla por 3, 10, 25, 100, 500 y 1,000 victorias consecutivas."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (dominación)\nSe gana medalla por 100, 500, 1,000 y 10,000 victorias en total."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla (dominación)\nSe gana medalla por 100, 500, 1,000 y 10,000 victorias en total."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Entrenamiento tanque Gattling"
Remove extra "t".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Bombardero de alfombra"
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "DescargaComunicaciones: &D"
Replace with "Descarga de comunicaciones" to reflect US string changes.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Cañón Gattling: &C"
Remove extra "t"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Cáscaras nucleares: &N"
Should be "Proyectiles de neutrones".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "PISTA:\nAdquiere el cañón teledirigido centinela en la Fábrica de Guerra."
Should be "PISTA:\nAdquiere la mejora del cañón teledirigido centinela en la Fábrica de Guerra." to reflect US strings changes.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "PISTA:\nLas ondas del tanque de microondas hieren a la infantería cercana."
Should be now: "PISTA:\nEl tanque de microondas fríe a la infantería cercana." to reflect US string changes.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "PISTA:\nLos Vengadores son unidades de apoyo que pueden neutralizar misiles y atacar aviones."
Replace "Vengadores" with "Avengers" (in other words, keep the original name unlocalized).

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "PISTA:\nUsa el Leaflet Drop para inhabilitar unidades enemigas."
Should be "PISTA:\nLanza propaganda para inutilizar unidades enemigas."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "PISTA:\nMejorar el bombardero invisible con antibúnker\npuede dañar a enemigos guarnecidos."
To reflect suggested changes, should be: "PISTA:\nMejorar el bombardero invisible con antibúnker\npuede matar a infantería guarnecida, minimizando el daño a la estructura."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "PISTA:\nUsa el poder de general Frenesí para que tus unidades tengan\nmás potencia de fuego y blindaje."
Should be now: "PISTA:\nUsa el poder de general Frenesí para aumentar temporalmente\nla potencia de fuego y blindaje."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "PISTA:\nSatellite Hack 2 revela de forma intermitente todo lo que las unidades enemigas pueden ver."
Should be: "PISTA:\nPirateo de satélite 2 revela intermitentemente cuánto pueden ver las unidades enemigas."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "PISTA:\nUsa el ataque furtivo para hacer una red de túneles\ninstantánea allá donde puedas ver."
Replace "hacer" with "crear" to reflect US string changes.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "PISTA:\nLos artilleros de minigun llevan un cañón Gattling."
Remove extra "t".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "PISTA:\nEl tanque Emperor puede mejorarse con un cañón Gattling."
Remove extra "t".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "PISTA:\nLa habilidad Demoliciones permite que todas las unidades detonen después de morir o cuando tú lo ordenes."
Should be "PISTA:\nLa capacidad de demoliciones permite que las unidades detonen después de morir o cuando lo ordenes."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "PISTA:\nCaptura el puesto espía para llamar a los Bombardero de alfombra."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "TRANSMISIÓN:\nLos Bombardero de alfombra están listos."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Construye un Cañón Gattling en este Helix."
Remove extra "t".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Aumenta la velocidad del Emperador Overlord y del Maestro de batalla en un 25 %."
Should be now: "Aumenta la velocidad al Emperor Overlord y Battlemaster en un 25%."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Transporte pesado\nSe puede mejorar con estructuras de defensa de base y bombas de napalm\n\nFuerte contra tanques, vehículos ligeros\nDébil contra soldados con cohetes, defensas antiaéreas"
Should be: "Transporte elevador pesado.\nSe puede actualizar con estructuras de defensa de base y bombas de napalm.\n\nEficaz contra tanques y vehículos ligeros\nDébil contra infantería con misiles y defensas antiaéreas"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Todos los tanques Gattling pasarán a ser élite."
Remove extra "t"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Tus unidades hacen más daño por un tiempo cuando se las apunta.\n\nRango 1: 10 por ciento durante 10 segundos\nRango 2: 20 por ciento durante 20 segundos\nRango 3: 30 por ciento durante 30 segun
Should be now: "Aumenta temporalmente la potencia de fuego de las unidades apuntadas\n\nRango 1: +10% de potencia por 10 segundos\nRango 2: +20% de potencia por 20 segundos\nRango 3: +30% de potencia por 30 segundos\n\nDespliegue desde: Centro de mando"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Aunque el GLA no necesita energía, China y los EE.UU. la devoran como palomitas. Para mantener fuerte una base, hay que gastar dinero en mucha energía para alimentar la maquinaria de guerra. Con
Should be now: "Aunque el GLA no necesita energía, China y los EE.UU. la devoran como palomitas. La falta de energía dejará tu producción y tus defensas en desventaja. Construye un reactor de fusión fría o un reactor nuclear para un rendimiento máximo. Sin energía, no tendrás ninguna oportunidad en esta guerra."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "General, asegúrate de construir cantidad de trabajadores, camiones de suministros o Chinook para que tus ingresos fluyan. Puedes crear recolectores extra haciendo clic en el centro o reserva de
Replace "crear" with "adquirir".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Algunas unidades pueden disparar o eliminar a los conductores enemigos de un vehículo. Cuando eso ocurre, los vehículos se hacen neutrales y pueden tomarse \"prestados\". Eres libre de darte una
Replace "un vehículo" for "los vehículos" to reflect US string changes.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Algunos edificios pueden mejorarse a camuflaje, como la red de túneles del GLA o los emplazamientos Stinger. El enemigo no podrá verlos hasta que sea demasiado tarde. ¡Sorpresa!"
Replace "los emplazamientos Stinger" with "el emplazamiento de Stingers".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "\nAviso: detectado cañón de partículas."
For consistency with the base game voice over, it should be: "\nAtención: se ha detectado un cañón de partículas."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "\nBien hecho, general. Has alcanzado un rango superior."
For consistency with the base game voice over, it should be: "\nMuy bien, general. Ha subido de rango."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "\nFelicidades. Te han ascendido."
For consistency with the base game voice over, it should be "\nEnhorabuena, general. Ha sido ascendido."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "\nGeneral, he contactado con uno de nuestros puestos espía.\nLes está atacando el GLA. Si les rescatamos,\npuedo entrar en su sistema y pedir Bombardero de alfombra."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "\nAlerta, posible bomba incendiaria aproximándose."
For consistency with the base game voice over, it should be "\nAlerta, podría aproximarse un bombardero incendiario."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "\nAlerta, posible bomba de fragmentación aproximándose."
For consistency with the base game voice over, it should be: "\nAlerta, podría aproximarse una bomba de fragmentación antipersona."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "\nAviso: se ha detectado un ataque furtivo."
I couldn't find any audio referring to this string in Spanish, but to keep consistency, "Aviso:" should be replaced with "Atención:" for consistency.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "\nAviso: Se ha activado un codificador GPS."
To keep word consistency with base game voice over, replace "Aviso:" with "Atención". The "S" of "Se" should be lowercase as well.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "\nAviso: detectado codificador GPS."
To keep word consistency with base game voice over, it should be: "\nAtención: se ha detectado un codificador GPS."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "\nNuestro nuevo Bombardero de alfombra siembra de bombas\nuna ruta objetivo, diezmando al enemigo."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "\nEl Bombardero de alfombra es un avión que siembra de bombas\nuna ruta objetivo, diezmando al enemigo."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "\nEl Bombardero de alfombra es un avión que siembra de bombas\nuna ruta objetivo, diezmando al enemigo."
Revert change.

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Transporte elevador pesado.\nSe puede actualizar con estructuras de defensa de base y bomba nuclear\n\nPotente contra tanques, vehículos ligeros\nDébil contra infantería con misiles, defensas an
Replace "bomba nuclear" with "bombas nucleares".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Transporte elevador pesado de asalto.\nSe puede actualizar con búnker y bomba de napalm.\n\nPotente contra tanques, vehículos ligeros\nDébil contra infantería con misiles, defensas antiaéreas"
Replace "bomba" with "bombas".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Aumenta la velocidad del Emperador Overlord y del Maestro de batalla en un 25 %."
Should be now: "Aumenta la velocidad del Emperor Overlord y Battlemaster en un 25%."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Base de defensa y túnel subterráneo. Dispara un chorro de toxina. Las unidades pueden entrar en la red de túneles y salir por cualquier otro túnel de la red."
Replace "toxina" with "toxinas".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "+25% de daños por impacto a Battlemaster y Emperor."
Should be now: "+25% de daños por impacto para Battlemaster y Emperor Overlord."

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Trampa de demolición avanzada\nCapacidad de demoliciones\nLos terroristas hacen más daño\nEmpieza con trampa explosiva\nLas motos de combate empiezan con terrorista\nSin unidades camufladas\nSin
Add "un" between "con" and "terrorista".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "Añade un cañón Gattling a este Emperor."
Remove extra "t"

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  ES: "El ataque supersónico hace al Aurora inmune al fuego enemigo. Después de un ataque supersónico, su velocidad se reduce en un 50%. Equipado con un láser de defensa de puntos.\n\nPotente contra ed
Replace "Potente" with "Eficaz". Delete comma after "misiles", then add an "y" between "misiles" and "defensas".

2025-03-12 17:14 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "En sigilo\nEquipado con un láser de defensa puntual\n\nFuerte contra las defensas de la base\nDébil contra los soldados con cohetes"
Should be: "Invisible.\nEquipado con láser de defensa de puntos.\n\nEficaz contra defensas de base\nDébil contra infantería con misiles"

2025-03-24 12:12 UTC, dmgreeny commented
This pull request can be closed.
All changes were moved here https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2727

2025-03-24 18:57 UTC, closed without merging