German localization fixes and improvements
TheSuperHackers/GeneralsGamePatch pull request #2536
Opened 2024-11-06 16:52 UTC by xezon

German localization fixes and improvements

2024-12-22 10:44 UTC, xezon reviewed
A number of edits need to be reverted. Please move edits that can be bundled with other language edits, where it makes sense, into separate changes.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Violett"
Violett is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Hitzesignaturen hinter Gebäuden EIN"
Hitzesignaturen is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Hitzesignaturen hinter Gebäuden AUS"
Hitzesignaturen is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Wertungsbildschirm"
Wertungsbildschirm is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Asynchron"
Asynchron is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "C&C Generäle - Die Stunde Null läuft nicht mehr synchron. Möglicherweise haben einige Mitspieler ihre Version des Spiels verändert. C&C Generäle - Die Stunde Null kann nicht fortgesetzt werden.
Ignorierliste

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Inoffiziell"
Inoffiziell is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Informiere dich über die bevorstehende Schlacht, mögliche Nachschublager und Hightech-Gebäude oder wähle deinen Startpunkt."
"deinen" is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Kopiere die gewählte Wiederholungsdatei auf deinen Desktop."
Wiederholungsdatei is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Wähle die Lautsprecherkonfiguration."
"Wähle die Lautsprecherkonfiguration" is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Wähle eine Befehlskategorie."
"Wähle eine Befehlskategorie." is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Wähle die Lautsprecher-Konfiguration. Das Spiel hat bereits die optimalen Einstellungen gewählt. Du kannst diese natürlich jederzeit ändern."
"Wähle die Lautsprecher-Konfiguration..." is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Sortiert nach Spielnamen."
Spielnamen is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Die Auszeichnungen eines Spielers. Wenn du im Einzelspieler- oder Multiplayer-Modus bestimmte Ziele erreichst, bekommst du Auszeichnungen."
erreichst is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Land wählen"
"Land wählen" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Anmeldung gescheitert - Andere Spielversion."
"Spielversion" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Lädt ein Spiel in %ls."
"Lädt" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Luftlandetruppen"
"Luftlandetruppen" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Installiere vor der Anmeldung bei Generäle - Die Stunde Null Online das aktuellste Update."
"aktuellste" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Anschluss an Channel nicht möglich."
"Anschluss an Channel nicht möglich." is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Die gemeinsamen Internetkomponenten wurden nicht installiert."
"Internetkomponenten" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Aktualisiere die gemeinsamen Internetkomponenten. Du findest sie auf der C&C Generäle - Die Stunde Null-CD."
"Internetkomponenten" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Blende die Menüleiste ein/aus."
"Blende" is more consistent with how the other German descriptions nearby are worded.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Wähle alle militärischen Einheiten aus."
"Wähle" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Nächster Arbeitsbot"
"Arbeitsbot" is correct. Several times in this file.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Wähle den nächsten Arbeitsbot."
"Wähle" is correct. Several times in this file.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Erstelle aus den markierten Einheiten Team 0."
"Erstelle" is more consistent with the other German descriptions texts. Several times in this file.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Wähle die Mitglieder von Team 0."
"Wähle" is correct. Several times in this file.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Kontaminieren: &K"
"Kontaminieren" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Cyborg-Trupp bewaffnen: &B"
"bewaffnen" is correct. Several times in this file.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Arbeitsbot: &A"
"Arbeitsbot" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Mit 20mm-Geschütz feuern: &F"
"feuern" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Apartmentanlage"
"Apartmentanlage" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Ziegelmauer"
"Ziegelmauer" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Schaufelbagger"
"Schaufelbagger" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Spiel beenden"
"Spiel beenden" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Du hast ein Nachschublager der WA-Army befreit. Hier werden die Rohstoffe, die du für den Bau neuer Einheiten und Gebäude brauchst, gelagert. Jedes Nachschublager wird von einem Chinook-Transpor
"ein" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Du hast einen Bulldozer der WA befreit. Linksklicke auf den Bulldozer, um dessen Bau-Liste einzublenden. Markiere in der Liste die Waffenfabrik und bestimme einen geeigneten Standort. Nach dem B
"einzublenden" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Du hast den Fusionsreaktor der Westlichen Allianz befreit. Die Westliche Allianz und der Asiatische Pakt versorgen ihre Stützpunkte mit Atomenergie. Die Energieleiste zeigt das Energieniveau dei
Original text is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Du hast den WA-Stützpunkt befreit und bist jetzt kampfbereit. Du musst in jeder Mission bestimmte Einsatzziele erreichen, um die Mission zu meistern und das nächste Kapitel des Spiels freizuscha
"Einsatzziele" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Deine Ranger können Hightech-Gebäude erobern. Wenn du diese Gebäude hältst, bist du deinen Feinden gegenüber im Vorteil. Erobere nun die Ölfördertürme. Wähle dazu einen Ranger aus, klicke auf di
Original text is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Bringt Ranger ins Zielgebiet. Wenn du sie auf einem besetzten Gebäude absetzt, werden die dort stationierten Einheiten neutralisiert."
"auf" is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Hackt dich ins Internet, um Geld zu stehlen."
"Hackt das Internet, um Geld zu stehlen."

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Alle neu gebauten Nuklear- und Infernalgeschütze haben den Status \"Veteran\"."
"Infernalgeschütze" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Halte feindliche Fahrzeuge mit einem Sicherheitszaun auf. Berührt ein Cyborg den Zaun, wird Alarm ausgelöst."
Original text is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Feuert Tomahawks auf einen bestimmten Ort ab."
Original text is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Rufe das Erfahrungsmenü auf, um deine in der Schlacht gewonnenen Erfahrungspunkte in Spezialfähigkeiten der Generäle einzutauschen."
"einzutauschen" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Minen räumen: &I"
"Minen räumen" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Klicke noch einmal auf Start, um den Sandkasten-Modus zu aktivieren."
Original text is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "– Black Bot muss die Fabrik finden"
"Black Bot" is correct. Several times in this file.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "– Splittergruppe in Bokmenistan enttarnt"
Original text is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "– Wir haben in Tarmah neue Verbündete gefunden"
"Tarmah" is just a made up location. Keep it.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Eisenbahnwagon"
"Eisenbahnwagon" is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Die Option QuickMatch wird versuchen, dich mit anderen Spielern entsprechend deines Könnens, PC-Eigenschaften etc. zu verbinden."
Original text is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Kampagne Eins"
Original is correct. Several times in this file.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Sende ..."
Sende is correct.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Tarmah"
It is risky to change this, because if the German voice over says "Tarmah", then the text will be inconsistent now.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Bazar"
It is risky to change this, because if the German voice over says "Bazar", then the text will be inconsistent now.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Hightower Fortress"
This English word is mentioned twice. Change it at both places.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Es kann sein, dass die betreffende Person versucht, die Verbindung wieder herzustellen. Aus diesem Grund solltest Du warten bis der Countdown abgelaufen ist. In diesem Fall wird der Spieler auto
"Es kann sein, dass die betreffende Person versucht die Verbindung wieder herzustellen. Aus diesem Grund solltest Du warten, bis der Countdown abgelaufen ist. In diesem Fall wird der Spieler automatisch entfernt und das Spiel wird fortgesetzt."

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Spieler möchte einen Buddy hinzufügen."
Original text is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Fanatismus: &F"
I would prefer all Fanaticism and Patriotism fixes across all languages in one single separate change.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "TIPP:\nDer Avenger kann feindliche Ziele markieren.\nEinheiten, die auf markierte Ziele feuern, verursachen mehr Schaden."
Original text is correct.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "NACHRICHT:\nSchleichangriff verfügbar.\nLegen Sie jetzt unauffällig Tunnelsysteme an."
Original text is ok.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  CONTROLBAR:TooltipUpgradeChinaFusionReactors
There are also
`CONTROLBAR:TooltipUpgradeChinaNuclearTanks`
`CONTROLBAR:Tank_TooltipUpgradeChinaNuclearTanks`
with similar text.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  CONTROLBAR:TooltipUpgradeChinaFusionReactors
Add comment:

```
// Alias CONTROLBAR:Tank_TooltipUpgradeChinaFusionReactors
CONTROLBAR:TooltipUpgradeChinaFusionReactors
```

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Verbessert die Geschwindigkeit von Emperor und Battlemaster."
"Verbessert die Geschwindigkeit von Emperor Overlord- und Battlemaster-Panzer."

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Schalten Sie in den Gebäude-Modus um."
Original is ok.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Bietet Platz für 8 Cyborgs, die aus dem Bus feuern können."
"feuern" is correct.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Sie haben meine Panzer besiegt, General.\nAber die Tigerin wird Sie zerquetschen wie ein Insekt!"
Original text is correct.

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "General, die Rohstoffbeschaffung kann im Verlauf einer Mission schwierig werden. Alle Kriegsparteien finanzieren ihre Armee anders. Der asiatische Pakt vertraut beispielsweise auf Hacker und Web
"vorausplanst" is ok

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Bestimmte Einheiten können Fahrzeuge entführen. Wenn du ein feindliches Fahrzeug mit einem Entführer oder einer fahrenden Bombe kaperst, kannst du unerkannt in feindliche Gebiete vorstoßen."
"kaperst" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Nur wenn du frühzeitig eine Kaserne errichtest, kannst du eine ausgewogene Armee aufbauen. Cyborgs haben schon so manche Schlacht entschieden. Vergiss das nicht!"
"errichtest" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Feuern mehrere MiGs oder Infernalgeschütze auf ein Ziel, kann der Asiatische Pakt einen Feuersturm entfesseln. Je besser du deine Angriffe koordinierst, desto effektiver bist du!"
"koordinierst" is correct

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Battlemaster und Emperor sind 25% schneller."
The the same wording style from `CONTROLBAR:TooltipUpgradeChinaFusionReactors`

2024-12-22 10:44 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "The friend request has been accepted"
This should be combined with the other languages that added text here into a single change.

2024-12-23 09:21 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Fanatismus: &F"
It will be done after you approve US loca changes

2024-12-23 09:23 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  CONTROLBAR:TooltipUpgradeChinaFusionReactors
Not sure what to do here

2024-12-23 09:30 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "The friend request has been accepted"
Its already done in TBD edits

2024-12-23 09:32 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  CONTROLBAR:TooltipUpgradeChinaFusionReactors
Fixed

2024-12-23 09:32 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  CONTROLBAR:TooltipUpgradeChinaFusionReactors
fixed

2024-12-23 09:32 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Verbessert die Geschwindigkeit von Emperor und Battlemaster."
fixed

2024-12-23 09:33 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Battlemaster und Emperor sind 25% schneller."
fixed

2024-12-25 07:56 UTC, xezon reviewed
It looks like something went wrong with text search and replace.

2024-12-25 07:56 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -FR: "Quitter Campagne"
This French edit does not belong here. Several times in this file.

2024-12-25 07:56 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Datei wählen"
"Datei wählen" was correct

2024-12-25 07:56 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Du kannst maximal %d Einheiten gleichzeitig ausWähle."
This is wrong.

2024-12-25 07:56 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Karte Wähle"
Original is correct. Several times in this file.

2024-12-25 11:56 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -FR: "Quitter Campagne"
fixed

2024-12-25 11:58 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Datei wählen"
fixed

2024-12-25 11:58 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Du kannst maximal %d Einheiten gleichzeitig ausWähle."
fixed

2024-12-25 11:58 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Karte Wähle"
Can you highlight all other cases?

2025-01-09 19:57 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Land wählen"
It is still not correct.

2025-01-09 20:00 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Wähle den nächsten Arbeitsbot."
This is still not correct.

2025-01-09 20:09 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  CONTROLBAR:TooltipUpgradeChinaFusionReactors
The proposal was to keep the wording consistent across these 3 tooltips because they are similar.

2025-01-09 20:11 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  CONTROLBAR:TooltipUpgradeChinaFusionReactors
Prefer no line break after `// Alias ...` comment (all the other alias comments are like that)

2025-01-09 20:15 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Battlemaster und Emperor sind 25% schneller."
Wording style is not consistent.
```
DE: "Emperor Overlord und Battlemaster-Panzer sind 25% schneller."
```
```
DE: "Verbessert die Geschwindigkeit von Emperor Overlord und Battlemaster-Panzer."
```

You can for example write

```
DE: "Verbessert die Geschwindigkeit von Emperor Overlord und Battlemaster-Panzer um 25%."
```

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Karte Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Spiel Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Campagne"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Spieler aus dem Spiel Wähle, um fortzufahren."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Startposition. Klicke, um diese als deine Startposition auf der Karte auszuWähle."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne USA\nTerminez la Campagne des USA pour obtenir cette récompense. Gagnez au niveau difficile pour recevoir la plus haute distinction."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne Chine\nTerminez la Campagne de la Chine pour obtenir cette récompense. Gagnez au niveau difficile pour recevoir la plus haute distinction."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne GLA\nTerminez la Campagne de la GLA pour obtenir cette récompense. Gagnez au niveau difficile pour recevoir la plus haute distinction."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "RANGLISTE Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Die Verbindung zum Buddy-Server wurde getrennt. Erneut anWähle?"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Channel konnte nicht Erstelle werden."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Erstelle Channel"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Nichts Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Alle Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Vorheriger Arbeitsboot"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Wähle Sie den vorherigen Arbeitsboot."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Doppelklicke auf eine Einheit, um alle Einheiten dieses Typs auszuWähle."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Team 0 Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Team 1 Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Team 2 Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Team 3 Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Team 4 Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Team 5 Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Team 6 Wähle"
This is wrong several times.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Cyborg-Trupp bewaffnung: &O"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Untätiger Arbeitsboot"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Cyborg-Trupp bewaffnung"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Du hast die WA-Kommandozentrale befreit. In der Zentrale kannst du deine Spezialfähigkeiten einsetzen. Klicke auf die blinkende General-Schaltfläche, wenn du eine Technologie oder eine Spezialwa
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Spiel konnte nicht Erstelle werden."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Server-Fehler - Account kann nicht Erstelle werden."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Schwierigkeitsgrad Wähle:"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "– Plündern Sie die brennende Stadt Tarma"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne USA\nTerminez la Campagne des USA pour obtenir cette récompense.\nGagnez au niveau difficile pour recevoir la plus haute distinction."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne Chine\nTerminez la Campagne de la Chine pour obtenir cette récompense.\nGagnez au niveau difficile pour recevoir la plus haute distinction."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne GLA\nTerminez la Campagne de la GLA pour obtenir cette récompense.\nGagnez au niveau difficile pour recevoir la plus haute distinction."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Linksklicke auf die General-Schaltfläche in der rechten unteren Bildschirmecke, um eine neue Fähigkeit für deinen General auszuWähle. Nach jeder Beförderung stehen deinem General neue Fähigkeite
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "%hs Erstelle ein Spiel."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "IBG-Gebäude verfügen über unterirdische Bunker zum Schutz der Arbeitsboots. Nach der Zerstörung eines IBG-Gebäudes bleibt ein tiefes Loch zurück. Die dort versteckten Arbeitsboots bauen das Gebä
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Drei-Schluchten-Damm"
You changed this name but there are still 2 other strings that say "Drei Turbinen Damm"

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Karte ausWähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne Défi\nTerminez la Campagne Défi de Generals pour remporter cette récompense.\nTerminez la Campagne en mode difficile pour remporter la plus haute distinction."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne Défi\nTerminez la Campagne Défi de Generals pour remporter cette récompense.\nTerminez la Campagne en mode difficile pour remporter la plus haute distinction."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Alle Flugzeuge Wähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Flugzeugträger ausWähle"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "TIPP:\nBestimmen Sie das Zielgebiet des Spectres und Wähle\nSie die Gegner manuell aus."
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Wähle SIE EINE ARMEE"
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Alle Generäle sollten eine einfache Regel beherzigen: Die unteren Ränge sind das Rückgrat einer Armee. Ohne Bulldozer und Arbeitsboote kannst du keinen Stützpunkt errichten. Diese Einheiten lege
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Die Befehligung einer Armee ist nicht ganz einfach. Du kannst alle Einheiten per Mausklick einzeln ausWähle. Allerdings ist dies relativ mühsam. Klicke daher mit der linken Maustaste und ziehe e
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Schnelltasten erleichtern die Befehligung deiner Streitkräfte ungemein. Mit \"E\"' kannst du alle Einheiten eines Typs auf dem Bildschirm ausWähle. Willst du alle Einheiten auf dem Schlachtfeld
This is wrong.

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "*Be on alert, A Daisy Cutter bomb may be approaching"
Why is this changed to comma?

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "*Be on alert, An EMP Pulse bomb may be approaching"
Why is this changed to comma?

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "*Be on alert, A fuel-Air bomb may be approaching"
Why is this changed to comma?

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Siegesmedaille\nFür diese Auszeichnung musst du 3 Spiele in Folge gewinnen."
Why is this removed?

2025-01-09 20:26 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Blitzkrieg-Orden\nGewinne in 10 Minuten (oder schneller) gegen Computergegner!"
Why is this removed?

2025-03-02 19:55 UTC, r0b2g1t requested changes
I agree with the review by @xezon

2025-03-02 19:55 UTC, r0b2g1t commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Team 9 Wähle"
This is wrong.

2025-03-02 19:55 UTC, r0b2g1t commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Team 8 Wähle"
This is wrong.

2025-03-02 19:55 UTC, r0b2g1t commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Team 7 Wähle"
This is wrong.

2025-03-04 08:01 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Land wählen"
fixed

2025-03-04 08:01 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Aktualisiere die gemeinsamen Internetkomponenten. Du findest sie auf der C&C Generäle - Die Stunde Null-CD."
fixed

2025-03-04 08:03 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Wähle den nächsten Arbeitsbot."
fixed

2025-03-04 08:04 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> -DE: "Fanatismus: &F"
will do

2025-03-04 08:05 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  CONTROLBAR:TooltipUpgradeChinaFusionReactors
Can you provide me with correct lines for all of them?

2025-03-04 08:09 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
>  CONTROLBAR:TooltipUpgradeChinaFusionReactors
Fixed

2025-03-04 08:11 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Battlemaster und Emperor sind 25% schneller."
fixed

2025-03-04 08:12 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Karte Wähle"
fixed

2025-03-04 08:12 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Spiel Wähle"
fixed

2025-03-04 08:12 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Campagne"
fixed

2025-03-04 08:13 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Spieler aus dem Spiel Wähle, um fortzufahren."
fixed

2025-03-04 08:13 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Startposition. Klicke, um diese als deine Startposition auf der Karte auszuWähle."
fixed

2025-03-04 08:15 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne USA\nTerminez la Campagne des USA pour obtenir cette récompense. Gagnez au niveau difficile pour recevoir la plus haute distinction."
fixed

2025-03-04 08:16 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne Chine\nTerminez la Campagne de la Chine pour obtenir cette récompense. Gagnez au niveau difficile pour recevoir la plus haute distinction."
fixed

2025-03-04 08:16 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de Campagne GLA\nTerminez la Campagne de la GLA pour obtenir cette récompense. Gagnez au niveau difficile pour recevoir la plus haute distinction."
fixed

2025-03-04 08:17 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "RANGLISTE Wähle"
fixed

2025-03-04 08:30 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Drei-Schluchten-Damm"
fixed

2025-03-04 08:36 UTC, dmgreeny commented
All comments were addressed

2025-03-24 17:40 UTC, xezon commented on Patch104pZH/Design/Changes/v1.0/2536_German_localisation_fixes.yaml
> +  - fix: Additional improvements to descriptions
Add these to `750_german_text_errors.yaml`. No need for new yaml file here.

You can change the title in `750_german_text_errors.yaml` from

`Fixes some errors in German language strings` to `Fixes and improves German language strings`

2025-03-24 17:40 UTC, xezon commented on Patch104pZH/Design/Changes/v1.0/2536_German_localisation_fixes.yaml
> +  - fix: Fixed spelling mistakes
We do not really use past tense in change logs. It is always "this change fixes this and that".

2025-03-24 17:40 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 24/03/2025 Changes DE from "C&C Generäle - Die Stunde Null läuft nicht mehr synchron. Möglicherweise haben einige Mitspieler ihre Version des Spiels verändert. C&C Generäle
This text is quite long. Maybe just say that "Ignorieren-Liste" was changed. Then it is easier to see the diff from comment.

More than once in this file.

2025-03-24 17:40 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Wähle Sie den nächsten Arbeitsboot."
The original text is correct.

2025-03-24 17:40 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Die Westliche Allianz hat unseren Bunker eingenommen. Holen Sie ihn zurück."
The original text is ok.

2025-03-24 18:04 UTC, dmgreeny commented on Patch104pZH/Design/Changes/v1.0/2536_German_localisation_fixes.yaml
> +  - fix: Additional improvements to descriptions
fixed

2025-03-24 18:04 UTC, dmgreeny commented on Patch104pZH/Design/Changes/v1.0/2536_German_localisation_fixes.yaml
> +  - fix: Fixed spelling mistakes
Noted

2025-03-24 18:07 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 24/03/2025 Changes DE from "C&C Generäle - Die Stunde Null läuft nicht mehr synchron. Möglicherweise haben einige Mitspieler ihre Version des Spiels verändert. C&C Generäle
fixed

2025-03-24 18:08 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Wähle Sie den nächsten Arbeitsboot."
fixed

2025-03-24 18:08 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Die Westliche Allianz hat unseren Bunker eingenommen. Holen Sie ihn zurück."
fixed

2025-03-24 18:20 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Wähle Sie den nächsten Arbeitsbot."
"Wähle den nächsten Arbeitsbot."

2025-03-24 18:25 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Wähle Sie den nächsten Arbeitsbot."
fixed

2025-03-24 18:45 UTC, xezon commented
Looks good to me. dmgreen you can approve this change. It needs to be rebased before it can be merged.

2025-03-24 18:54 UTC, dmgreeny approved these changes

2025-03-24 18:55 UTC, dmgreeny commented
Approved

2025-03-24 18:55 UTC, r0b2g1t approved these changes

2025-03-24 18:55 UTC, r0b2g1t commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +DE: "Wähle Sie den nächsten Arbeitsboot."
it is not correct. Change it to:
Wähle den nächsten Arbeitsbot.

2025-04-01 11:43 UTC, closed without merging