French localization fixes and improvements
TheSuperHackers/GeneralsGamePatch pull request #2537
Opened 2024-11-06 16:52 UTC by xezon

French localization fixes and improvements

2025-01-09 20:39 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Partie :"
You have changed all whitespace of code 160 to space of code 32. This is wrong.

The whitespace 160 intends to not break line. See
https://stackoverflow.com/questions/2132348/what-does-char-160-mean-in-my-source-code

Please keep whitespace code 160 as is.

Several hundred times in this file.

2025-03-02 15:08 UTC, TheMatthew requested changes
Minor nits.

2025-03-02 15:08 UTC, TheMatthew commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Es Carmouche"
Escarmouche means Skirmish. https://www.larousse.fr/dictionnaires/francais/escarmouche/30954

2025-03-02 15:08 UTC, TheMatthew commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "ASTUCE :\nAméliorez le pouvoir de général chasseur de primes pour augmenter vos revenus."
In this case, the family name of the general is Chasseur, and should be capitalized.

2025-03-02 15:08 UTC, TheMatthew commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Les ouvriers reçoivent les nouvelles chaussures qu'ils demandent, ce qui accroît leur vitesse de déplacement."
Both sentences are correct, need to see the original to be certain.

2025-03-02 15:08 UTC, TheMatthew commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Le Spectre survole le champ de bataille et pilonne les troupes ennemies avec des obusiers et des mitrailleuses Gattling.\n\nDéployé depuis : Poste de commandement."
Gatling, one T

2025-03-02 15:08 UTC, TheMatthew commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Général, vous ne pouvez rien contre la toxine Gamma. Une défaite ne vous suffit donc pas ?"
Original was correct too.

2025-03-03 13:50 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Balles incapacitants: &B"
The original translation is the correct one

2025-03-03 13:50 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Armer les Émeutes"
The original translation is the correct one

2025-03-03 20:44 UTC, Alex-PLACET requested changes
Done until l.14743

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Hélicoptère de transport d'assaut. Récupérer du ravitaillement. Coopère avec les Rangers pour les parachuter. Équipé d'un laser défensif."
'Récupère' is the right translation

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Désactive les bâtiments et neutralise les véhicules avec un virus informatique ou piraté Internet pour voler de l'argent. Unité camouflée.\n\nEfficace contre les bâtiments.\nVulnérable face à l'
```suggestion
FR: "Désactive les bâtiments et neutralise les véhicules avec un virus informatique ou pirater Internet pour voler de l'argent. Unité camouflée.\n\nEfficace contre les bâtiments.\nVulnérable face à l'infanterie et les véhicules."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "*Warning: GPS Scrambler Detected"
```suggestion
FR: "*Avertissement: brouilleur GPS détecté"
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "*Be on alert, A fuel-Air bomb may be approaching"
```suggestion
FR: "*Alerte, possible bombe en approche"
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "*Be on alert, An EMP Pulse bomb may be approaching"
```suggestion
FR: "*Alerte, possible bombe EMP en approche"
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "*Be on alert, A Daisy Cutter bomb may be approaching"
```suggestion
FR: "*Alerte, possible bombe Daisy Cutter en approche"
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "A quoi bon collectionner des points de général si vous ne les utilisez pas ? Si vous achetez des pouvoirs de général en utilisant vos points, un icône apparaîtra sur la droite de votre écran. Vo
```suggestion
FR: "A quoi bon collectionner des points de général si vous ne les utilisez pas ? Si vous achetez des pouvoirs de général en utilisant vos points, une icône apparaîtra sur la droite de votre écran. Vous n'avez qu'à cliquer dessus pour profiter d'un beau feu d'artifice. Plus vous dépenserez de points, plus les effets du pouvoir fraîchement acquis seront dévastateurs."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Ce choix sélectionne aléatoirement votre faction."
```suggestion
FR: "Ce choix sélectionnera aléatoirement votre faction."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Nous n'en resterons pas là. A bientôt, en général."
```suggestion
FR: "Nous n'en resterons pas là. A bientôt général."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "C'est impossible ! J'exige une revanche, en général !"
```suggestion
FR: "C'est impossible ! J'exige une revanche, général !"
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Charge aux ogives nucléaires."
```suggestion
FR: "Charger les ogives nucléaires."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Les ouvriers reçoivent les nouvelles chaussures qu'ils demandent, ce qui accroît leur vitesse de déplacement."
I prefer the first one

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Accroche la résistance des bâtiments."
```suggestion
FR: "Accroît la résistance des bâtiments."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Accroche la cadence de tir des Maîtres de guerre."
```suggestion
FR: "Accroît la cadence de tir des Maîtres de guerre."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Accroche la vitesse des Chars Emperor, Empereurs et Maîtres de guerre."
```suggestion
FR: "Accroît la vitesse des Chars Emperor, Empereurs et Maîtres de guerre."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Construis un bunker chinois sur cet Hélix. Des troupes peuvent faire feu depuis ces bunkers."
```suggestion
FR: "Construit un bunker chinois sur cet Hélix. Des troupes peuvent faire feu depuis ces bunkers."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Construis une Mitrailleuse Gatling sur cet Hélix."
```suggestion
FR: "Construit une Mitrailleuse Gatling sur cet Hélix."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Construit un Haut-parleur d'embrigadement sur cet Hélix. Soignez vos troupes et augmentez leur cadence de tir."
```suggestion
FR: "Construit un Haut-parleur d'embrigadement sur cet Hélix. Soigne vos troupes et augmente leur cadence de tir."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Construit un Haut-parleur d'embrigadement sur cet Hélix. Soignez vos troupes et augmentez leur cadence de tir."
```suggestion
FR: "Construit un Haut-parleur d'embrigadement sur cet Hélix. Soigne vos troupes et augmente leur cadence de tir."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Attente de la réponse de la sonde..."
```suggestion
FR: "Attente de la réponse de sonde..."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de campagne USA\nTerminez la campagne des USA pour obtenir cette récompense. Gagnez un niveau difficile pour recevoir la plus haute distinction."
```suggestion
FR: "Distinction de campagne USA\nTerminez la campagne des USA pour obtenir cette récompense. Gagnez au niveau difficile pour recevoir la plus haute distinction."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de campagne Chine\nTerminez la campagne de la Chine pour obtenir cette récompense. Gagnez un niveau difficile pour recevoir la plus haute distinction."
```suggestion
FR: "Distinction de campagne Chine\nTerminez la campagne de la Chine pour obtenir cette récompense. Gagnez au niveau difficile pour recevoir la plus haute distinction."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Distinction de campagne GLA\nTerminez la campagne de la GLA pour obtenir cette récompense. Gagnez un niveau difficile pour recevoir la plus haute distinction."
```suggestion
FR: "Distinction de campagne GLA\nTerminez la campagne de la GLA pour obtenir cette récompense. Gagnez au niveau difficile pour recevoir la plus haute distinction."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Connexion au serveur mais refusée."
```suggestion
FR: "Connexion au serveur ami refusée."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Recherche de la part de l'adversaire..."
```suggestion
FR: "Recherche de la partie de l'adversaire..."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Temps d'attente pour rejoindre Generals - Heure H en ligne écoulée."
```suggestion
FR: "Temps d'attente pour rejoindre Generals - Heure H en ligne écoulé."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Aucun outil de recherche rapide trouvez."
```suggestion
FR: "Aucun outil de recherche rapide trouvé."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Les composants Internet partagés doivent être mis à jour. Veuillez l' installer à partir du disque de C&C Generals - Heure H."
```suggestion
FR: "Les composants Internet partagés doivent être mis à jour. Veuillez les installer à partir du disque de C&C Generals - Heure H."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Pour sélectionner l'ouvrage suivant."
```suggestion
FR: "Pour sélectionner l'ouvrier suivant."
```

2025-03-03 20:44 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Pour sélectionner l'ouvrage précédent."
```suggestion
FR: "Pour sélectionner l'ouvrier précédent."
```

2025-03-03 20:45 UTC, Alex-PLACET commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +FR: "Partie :"
This should be done asap as the review is really difficult as the diff is really big.

2025-03-05 13:41 UTC, dmgreeny commented
Thanks everyone for contribution. I fixed the issue with space and applied your suggestions. Please check them here
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2639
Also, please check French lines here:
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2571
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2535
This branch can be closed. We have a new fixed one here:
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2639

2025-03-05 13:51 UTC, xezon commented
Obsoleted pull.

2025-03-05 13:51 UTC, closed without merging