Spanish localization fixes and improvements
TheSuperHackers/GeneralsGamePatch pull request #2538
Opened 2024-11-06 16:53 UTC by xezon

Spanish localization fixes and improvements

2025-01-10 18:23 UTC, xezon reviewed
This needs to be reviewed by a Spanish native.

2025-01-11 22:44 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "SCARAMUZZA"
Original translation is correct. Revert.

2025-01-11 22:44 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Conectar el auto. en el futuro"
Original translation is correct. Revert.

2025-01-11 23:04 UTC, ElTioRata commented
I'm a bit new to reviewing this. I think it's better to review stuff that needs to be corrected? I think pointing out what's correct adds bloat to the review comments. Leave strings as they're if I didn't review them.

2025-01-11 23:39 UTC, xezon commented
Yes only point out things that were done incorrect.

2025-01-11 23:45 UTC, ElTioRata commented
Okay, done. Damn, that took me almost an hour.

2025-01-11 23:59 UTC, xezon commented
Well you also need to submit your review. We cannot see it until then.

2025-01-12 01:45 UTC, ElTioRata requested changes

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "SCARAMUZZA"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Conectar el auto. en el futuro"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "© 2003 ELECTRONIC ARTS INC. TODOS LOS DERECHOS RESERVADOS."
I'd keep the dot for consistency on the rest of the localizations although it isn't there on English.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Las condecoraciones del jugador\nSe consigue al alcanzar objetivos en modo de un jugador o multijugador."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Medalla por la lealtad a China\nHa jugado más de 20 partidos seguidos para China."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Rechazada la conexión con el servidor colega."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Cargado en %ls."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "No tienes dinero para mejorar."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Asignar una tecla directa"
I believe nowadays everyone translate "hotkey" to "tecla de acceso rápido" instead. "Asignar tecla de acceso rápido" would be better but it's a bit too long, so I'd change it to "Asignar atajo de teclado".

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Asignado a"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Conectado"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Desconectado"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Tu número de serie ya está en uso."
The new string is preferred but maybe someone should check that the string doesn't get cut off because maybe that's why they put "núm" instead of "número".

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Tu número de serie no es válido."
Same as above.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Recibí ping de %dms. Cuanto más bajo sea el ping, mejor será la conexión."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Conectado"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "%ls no están conectados."
Original translation is correct. Revert this change.

Although if "%ls" is referred to the user, maybe changing a few words to make it more neutral would improve it. Example: "%ls no está en línea"

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "%ls no están en ningún canal."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Ignorar al jugador."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Desplegar los objetos seleccionados."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Selecciona y centra la vista sobre el equipo 5."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Selecciona y centra la vista sobre el equipo 6."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Selecciona y centra la vista sobre el equipo 7."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Selecciona y centra la vista sobre el equipo 8."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Selecciona y centra la vista sobre el equipo 9."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Reparar"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Cañón Gatling: &C"
The improved string is correct. We don't write it with double "t".

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Tanque Gatling: &G"
Same as above.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Tanque Gatling: &A"
Same as above.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Cañón Gatling: &A"
Same as above.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Cañón Gatling: &A"
Same as above.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Bayonetta: &B"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Barracas"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Starlifter 2"
Maybe keep space for consistency on other languages?

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Arrastre"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Los americanos han vuelto a tomar nuestro búnker. ¡Recuérdalo ya!"
Original translation is correct. Revert this change. Also since this should be formal, change to "Recupérelo"

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "La base traidora está destruida.\nExtermina a las fuerzas que quedan para completar tu victoria."
Original translation is correct. Revert this change. Change "Extermina" for "Extermine" because it's formal.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Podrás despejar la niebla de la guerra, moviéndote hacia nuevas áreas sin explorar. El humo muestra dónde has explorado y dónde no. Exploran áreas nuevas para encontrar enemigos y recursos para
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Las cajas contienen objetos bonus para los soldados que aumentarán sus capacidades: munición adicional, armas, etc.. Ordena a tus soldados o vehículos que vayan hasta una caja, la abran y cojan
This one's is improved but I'd suggest changing "bonus" to "extras". I just can't recall the last time I saw that word untranslated on recent localizations.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Lanzaminas desde avión.\n\nCuenta atrás: 4:00"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Explotó cuando el enemigo se acerca."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Disparar misiles antitanque sobre el objetivo."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Disparar un solo cohete pesado sobre el objetivo."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Secuestró el vehículo objetivo enemigo."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Usar la bayoneta con el soldado enemigo objetivo."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Se usa para retener a los soldados enemigos capturados."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Construye todas las estructuras de E.E.U.U. Reparar puentes y edificios urbanos."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Helicóptero de transporte. Recoge suministros. Lleva Rangers para realizar lanzamientos de combate. Está equipado con un láser de defensa de puntos."
Original translation is correct. Revert this change. Although if the translator was trying to minimize words, I'd remove the "un" that comes after "Equipado con".

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "El ataque supersónico hace a Aurora inmune al fuego enemigo. Después de un ataque supersónico, su velocidad se reduce en un 50%.\n\nPotente contra edificios\nDébil contra infantería con misiles,
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Te permite pedir un bombardero para lanzar una bomba de impulso electromagnético que desactiva vehículos y edificios enemigos.\n\nDespliegue desde: Centro de mando"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Construir una barricada en llamas que incendie las unidades que intenten pasar."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Bombardeó con ántrax: &B"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "%ls ha derrotado."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Add a player to your list of Buddies."
Well, this should be translated. Should be "Agrega un jugador a tu lista de colegas".

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Dzhambul, territorio ocupado por China, Kazajstán\nOperación: Fuego Justificado"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "PISTA:\nUsa los lanza misiles Tomahawk para arrasar con los puntos estratégicos del GLA."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Explota un dispositivo nuclear oculto."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Clic izquierdo en el botón \"generales\" en la esquina inferior derecha de la pantalla para escoger una capacidad nueva para tu General. Conforme asciendes, el General accede a nuevas capacidade
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "QuickMatch intenta buscarte un jugador en función de la habilidad, espec. del PC, etc."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Comprueba que tienes DirectX 8.1 o superior instalado. Y comprueba que tu tarjeta de vídeo reúne los requisitos mínimos."
This one's correct now but I don't recall anyone saying "reúne los requisitos" when it comes to meeting PC requirements. We usually say "cumple" so I'd switch to that word instead.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Fallo al comunicarme con la red, comprueba tu conexión."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Crea una formación en las unidades seleccionadas y la retendrá cuando se muevan."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Es posible que algún jugador este intentando reconectar, así que puedes elegir esperar hasta que el tiempo s de este jugador concluye. Cuando el contador llegue a 0, esa persona será desconecta
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Patriotismo: &F"
I'm a bit conflicted with this one.
While the correction is _technically_ correct, the rest of the languages translated "Patriotism" as "Fanatism" too? Maybe the context is better fitted for that word instead so I'd revert it.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Permite que la capacidad de pirateo de satélite Y revele los centros de mando de los oponentes."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Desactiva edificios. Reinicia la cuenta atrás de superarmas."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "El ataque supersónico hace a Aurora inmune al fuego enemigo mientras lanza una pequeña bomba incendiaria. Después de un ataque supersónico, su velocidad se reduce en un 50%.\n\nPotente contra ed
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "El ataque hipersónico hace a Aurora inmune al fuego enemigo. Después de un ataque hipersónico, su velocidad se reduce en un 50%.\n\nPotente contra edificios\nDébil contra infantería con misiles,
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Pensabas que las toxinas no eran eficaces, y ahora mira lo que te ha pasado, general."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Te dije que jamás derrotarás a mis superarmas, general. ¿Te atreves de nuevo?"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "A veces es importante que las unidades se queden y vigilan una zona concreta. Selecciona una, pulsa el botón del \"escudo\" o la tecla \"G\" y elige la zona a proteger. La unidad atacará a todo
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Algunas unidades pueden entrar en vehículos o robarlos. Robar vehículos con secuestradores o terroristas puede permitirte infiltrarse en territorio enemigo"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "General, las teclas directas son un buen modo de aumentar el control de tus fuerzas. \"E\" seleccionará todas las unidades del mismo tipo de la pantalla de vista. Si pulsas \"E\" rápidamente dos
Original translation is correct. Revert this change. Also, change "teclas directas" to "teclas de acceso rápido" for consistency.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "General, hemos creado una nueva forma de dirigir tu ejército. Selecciona tus unidades y haz doble clic en la zona de destino. Éstas atacarán/avanzan a ese punto y luego lo protegerán. Puedes act
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "CARGAR REPRODUCCIÓN"
If this is replay as "match recording", the game already localized it as "REPETICIÓN" so it should be "CARGAR REPETICIÓN".

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "El ataque supersónico hace a Aurora inmune al fuego enemigo. Después de un ataque supersónico, su velocidad se reduce en un 50%. Equipado con un láser de defensa de puntos.\n\nPotente contra edi
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Helicóptero de transporte y asalto. Recoge suministros. Lleva rangers para realizar lanzamientos de combate. Está equipado con un láser de defensa de puntos."
I think I corrected this already. Revert change and delete the "un" after "Equipado con".

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "PISTA:\nEl hospital hará que tus unidades se curan automáticamente."
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Algunos edificios pueden mejorar su camuflaje, como la red de túneles del GLA o los emplazamientos Stinger. El enemigo no podrá verlos hasta que sea demasiado tarde. ¡Sorpresa!"
Original translation is correct. Revert this change.

2025-01-12 01:45 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Haz clic sobre las unidades para seleccionarlas y darles órdenes. Con una seleccionada puedes hacer clic en el suelo para que se mueva. Haz clic sobre los soldados enemigos para atacarlos con es
Original translation is correct. Revert this change.

2025-01-12 09:43 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Tu número de serie ya está en uso."
I suspect that is no problem because DE text is longer.

2025-01-12 09:45 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Patriotismo: &F"
Yes, this needs to be an isolated change for all languages and all strings that refer to "Fanatism".

2025-03-06 08:07 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Selecciona y centra la vista sobre el equipo 9."
What about 1 - 4?

2025-03-06 08:09 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Starlifter 2"
I will make it so

2025-03-06 08:31 UTC, dmgreeny commented
All comments fixed. Please check the changes again.
Also, please check Spanish lines here:
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2535
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2571

2025-03-06 10:31 UTC, keincrove commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Asignar una tecla directa"
Shouldn't it be "Asignar **nuevo** atajo de teclado" as og one says "...**new** hotkey"?

2025-03-06 17:51 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Asignar una tecla directa"
In a literal sense, yes. But it's a little bit too long compared to the other language strings. So I don't find it too necessary.

2025-03-06 17:52 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Selecciona y centra la vista sobre el equipo 9."
Oops, looks like I skipped those. Same protocol, revert to the original strings.

2025-03-10 18:30 UTC, ElTioRata commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +ES: "Honor militar\nDerrota oponentes IA en 10 minutos o menos para ganar esta medalla."
I'd like to revert my previous suggestion. Should be:
"Medalla (relámpago)\nDerrota oponente(s) en 10 minutos o menos para ganar esta medalla."

2025-03-25 08:36 UTC, dmgreeny approved these changes
All fixed and added. Can be double-checked now

2025-03-26 22:23 UTC, xezon reviewed
This change needs to be rebased, otherwise cannot be merged.

2025-03-26 22:23 UTC, xezon commented on Patch104pZH/Design/Changes/v1.0/2151_spanish_text_errors.yaml
> +
Can remove this blank line.

2025-03-26 22:23 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 25/03/2025 Changes ES to include "-" (#2538)
I suggest to just put one line for all of these to the top of this file:

`// Patch104p @fix dmgreen 25/03/2025 Adds missing dash to all LOAD string for ES (#2538)`

2025-03-27 06:38 UTC, dmgreeny commented on Patch104pZH/GameFilesEdited/Data/generals.str
> +// Patch104p @fix dmgreen 25/03/2025 Changes ES to include "-" (#2538)
Fixed

2025-04-01 11:43 UTC, closed without merging