Militia Tank and Bio Hazard Inf
TheSuperHackers/GeneralsGamePatch pull request #548
Opened 2021-10-10 17:44 UTC by Jundiyy

Updates for both.

2021-10-12 15:42 UTC, xezon commented
@Jundiyy I resolved conflicts with the game_balance.md file. Can you check if it is correct? It shows no longer a diff, which is suspicious in case you changed balance values. If you didn't, then it is good.

2021-10-12 15:45 UTC, xezon requested changes
Please provide a more descriptive headline for your change. It is not clear what "Militia Tank and Bio Hazard Inf" means on first sight.

Also, please document all your changes properly with **Patch104p** keyword.

Here is how commy2 and hanfield document their changes:
https://github.com/xezon/GeneralsGamePatch/pull/553/files

2021-10-18 08:09 UTC, Jundiyy commented
Changed the title, will do the Patch104p when on comp.

2021-10-18 08:33 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
> +  ButtonImage   = SUEnterbldg ;Could use a better image.
I like `SAChemsuit` for this.

2021-10-18 08:33 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
> +  ButtonImage   = SUEnterbldg ;Could use a better image.
Once can also add `SAChemsuit_L` as portrait for the unit.

2021-10-18 08:35 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaMiscUnit.ini
> +  ;End
If you comment blocks of code in this style:
```sqf
  ;Behavior = ExperienceScalarUpgrade ModuleTag_07
  ;  TriggeredBy = Upgrade_AmericaAdvancedTraining
  ;  AddXPScalar = 1.0 ;Increases experience gained by an additional 100%
  ;End
```
most text editors can undo the comment with a few clicks instead of going through it all line by line.

2021-10-18 08:38 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaMiscUnit.ini
> +  ;End
E.g. ST3: left click right of lowest semi-colon. Hold middle mouse button to draw a box over the whole coloumn of semi-colons. Then press backspace.

The current staggered pattern is a pita compared to that, especially if the code blocks become 10 or more lines.

2021-10-18 09:25 UTC, Jundiyy commented on Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
> +  ButtonImage   = SUEnterbldg ;Could use a better image.
I actually used that in my mod at first but after getting some play testing, players thought it was an upgrade and not a unit, so I chose this image instead.

2021-10-31 20:52 UTC, Jundiyy commented
These 2 units are ready to add.

2021-10-31 20:57 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaMiscUnit.ini
> +    ;Object = AmericaBarracks
Whitespace at end of line.

2021-10-31 20:58 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
> +  11 = Command_AttackMove ; Patch104p Jundiyy 10.10.2021 Ambualance also has this.
Ambulance doesn't have this, right?

2021-10-31 20:58 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaMiscUnit.ini
> +  AddXPScalar = 1.0 ;Increases experience gained by an additional 100%
Comment is wrong. Indentation seems off too.

2021-10-31 21:00 UTC, Jundiyy commented on Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
> +  11 = Command_AttackMove ; Patch104p Jundiyy 10.10.2021 Ambualance also has this.
Yep it does.

2021-10-31 21:01 UTC, Jundiyy commented on Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaMiscUnit.ini
> +  AddXPScalar = 1.0 ;Increases experience gained by an additional 100%
oh yea lol, I only re-added the code. Will do that now.

2021-10-31 21:01 UTC, Jundiyy commented on Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaMiscUnit.ini
> +    ;Object = AmericaBarracks
ty

2021-10-31 21:15 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
> +  KindOf                 = PRELOAD SELECTABLE CAN_ATTACK ATTACK_NEEDS_LINE_OF_SIGHT CAN_CAST_REFLECTIONS VEHICLE SCORE ;ATTACK_NEEDS_LINE_OF_SIGHT ; Patch104p Jundiyy 10.10.2021 = Stops it shooting t
The extra `;ATTACK_NEEDS_LINE_OF_SIGHT` should be remoced.

2021-10-31 21:16 UTC, Jundiyy commented on Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
> +  KindOf                 = PRELOAD SELECTABLE CAN_ATTACK ATTACK_NEEDS_LINE_OF_SIGHT CAN_CAST_REFLECTIONS VEHICLE SCORE ;ATTACK_NEEDS_LINE_OF_SIGHT ; Patch104p Jundiyy 10.10.2021 = Stops it shooting t
Can do, I added it in to so the reader knew what I'm referring to. What do you think?

2022-08-28 07:39 UTC, closed without merging