Tank Nuke Cannon and Inferno Cannon
TheSuperHackers/GeneralsGamePatch pull request #575
Opened 2021-10-17 15:35 UTC by Jundiyy

Mappers can now add Nuke Cannons and Inferno Cannons to the Tank General War Factory.

First they must use the CommandButton script to add these units to the War Factory, then they must also place down a TechWarFactory per player (off map is fine) and script them so they are given to each player. 

The second route is to add the CommandButtons scripts then add scripts to ignore prerequisites.

2021-10-18 07:18 UTC, commy2 commented
Couldn't the map maker not just do:
```map.ini
CommandSet Tank_SCIENCE_CHINA_CommandSetRank1
  3 = Command_PurchaseScienceNukeLauncher
End

CommandSet Tank_ChinaWarFactoryCommandSet
  9  = Command_ConstructChinaVehicleInfernoCannon
  10 = Command_ConstructChinaVehicleNukeLauncher
End

Object ChinaVehicleInfernoCannon
  Prerequisites
    Object = ChinaPropagandaCenter Tank_ChinaPropagandaCenter
  End
End

Object ChinaVehicleNukeLauncher
  Prerequisites
    Object = ChinaPropagandaCenter Tank_ChinaPropagandaCenter
    Science = SCIENCE_NukeLauncher
  End
End
```
That should work in 1.04 already.

2021-10-18 07:58 UTC, Jundiyy commented
This would require map.ini, which not everyone knows or a mapper may not want due to having to restart on transfer and after game.

Map makers can currently add any unit but have to remove the prerequisites through scripts, which means units can be built without tech.

The purpose of these units and some others is to allow a simple 'drag and drop', otherwise we could just ask all mappers to learn/use map.ini and no need to do changes. It's more of ease of access for them, find the units in WB and use them.

2021-10-18 08:02 UTC, xezon commented
With current map.ini tech it is desirable to reduce map.ini use cases, because it can cause mismatching in successive map loads.

2021-10-18 08:42 UTC, commy2 commented
And doesn't work immediately on transferred maps.

I think that is the underlying issue here and should be addressed, possibly by Thyme.

2021-10-18 09:28 UTC, xezon commented
Yes. For current developments however I believe we should not rely on Thyme and cater to original game executable as usual.

2021-10-18 11:07 UTC, xezon requested changes
Add Linebreak at end of file(s) and add comments to new added features.

2021-10-18 21:39 UTC, Jundiyy commented
Done.

2021-10-19 13:26 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
> +  ; Patch104p @bugfix commy2 09/09/2021 Prevent exploit that allows Neutron Shells without upgrade.
Would remove this, as that change is not made by this patch.

2021-10-19 13:26 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
> +  ; Patch104p @bugfix commy2 09/09/2021 Prevent exploit that allows Neutron Shells without upgrade.
ditto

2021-10-31 18:15 UTC, xezon approved these changes

2021-10-31 18:16 UTC, merged