Add: Repair Drone Implemention
TheSuperHackers/GeneralsGamePatch pull request #600
Opened 2021-10-28 20:45 UTC by Jundiyy

We could do with getting some voice lines for this unit, or stick with Sentry Drone lines.

Also not sure if it's too much work, but make the wheels go round.
And lastly I used Sentry Drone death models, they work and look better than Crusader ones but maybe we need unique?

2021-10-31 19:35 UTC, Jundiyy commented
This one is a new unit so can be added in.

2021-10-31 19:40 UTC, commy2 commented
It shouldn't be in "AmericaMiscUnit.ini", probably.

2021-10-31 19:43 UTC, Jundiyy commented
I was just about to ask if we should make a new ini file for the new units. Call it NewUnits.ini.
Thoughts?

2021-10-31 19:44 UTC, commy2 commented
These are for the TechFactory, right? If so, they should be associated with it, or at least all collected next to each other.

2021-10-31 19:47 UTC, Jundiyy commented
👍 Maybe a new file is best then.

2021-11-05 20:46 UTC, commy2 commented
https://user-images.githubusercontent.com/6576312/140576323-42cd1e4f-63f5-4ea7-b2c9-b24e0e27a839.mp4


https://user-images.githubusercontent.com/6576312/140576367-21f8a5d6-b9fe-4734-8435-94d9a04fba87.mp4



Further work is required, but I'm beat for today.

2021-11-06 13:49 UTC, commy2 commented
https://user-images.githubusercontent.com/6576312/140612003-56feb55b-8fda-460f-9f05-0479845d0c9e.mp4

2021-11-06 14:05 UTC, commy2 commented
https://user-images.githubusercontent.com/6576312/140612462-699c4db7-ef9b-4b9e-8b01-075336d3afc9.mp4

2021-11-06 17:15 UTC, commy2 commented
- [ ] squash before merging
- [ ] ui texts

Description should mention that it repairs buildings and nearby vehicles, and that it can finish construction of scaffolds.

2021-11-06 17:15 UTC, commy2 approved these changes

2021-11-09 14:19 UTC, xezon approved these changes

2021-11-09 14:19 UTC, xezon commented on Patch104pZH/Scripts/MAKE_Patch104pZH.bat
> +    xcopy /y    "%GameFilesDir%\Art\W3D\AVRepairDr_D.W3D"         "%GeneratedBigFilesUnpackedDir%\%BigName%\Art\W3D\"
Looks like the textures need to be added here as well.

2021-11-09 14:19 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SARepairDrone.INI
> +End
Any reason this is put into `TextureSize_512` as opposed to `HandCreated` folder? I do wonder, if game actually loads from custom Folder name as well, such as `MappedImages/Object/SARepairDrone.ini`. Can you try?

2021-11-09 14:20 UTC, xezon requested changes
Approved by mistake.

2021-11-20 11:21 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SARepairDrone.INI
> +End
Tried "Custom" as folder and image remained blank. It does work with "HandCreated" though.

The base game buttons and portraits are inside "TextureSize_512" though.

2021-11-20 11:24 UTC, commy2 commented on Patch104pZH/Scripts/MAKE_Patch104pZH.bat
> +    xcopy /y    "%GameFilesDir%\Art\W3D\AVRepairDr_D.W3D"         "%GeneratedBigFilesUnpackedDir%\%BigName%\Art\W3D\"
Done

2021-11-20 12:27 UTC, xezon commented on Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SARepairDrone.INI
> +End
Ok. It likely looks into specific predefined folders only then. Another thing to try would be `MappedImages/HandCreated/Object/File.ini`. I think it does not matter much where we put it right now, I do like `HandCreated` folder though, because the original game only has one ini file in there, so it is rather tidy and it becomes obvious that new ini files in there are added by Modders.

Up to you.

2021-11-20 12:27 UTC, xezon approved these changes

2021-11-21 03:07 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SARepairDrone.INI
> +End
This convinced me to change it.

2022-01-01 16:31 UTC, xezon commented
Looks like the **CONTROLBAR:ToolTipUSABuildRepairDrone** string can be added now.

2022-08-28 07:39 UTC, closed without merging