Add: Amphibious Transport Implementation
TheSuperHackers/GeneralsGamePatch pull request #601
Opened 2021-10-28 20:45 UTC by Jundiyy

Made a carbon copy of the unit instead, to give it more use in fun maps, old unit was really weak but didn't want to change stats as it could cause problems to maps that already use it.

2021-10-30 11:01 UTC, commy2 commented
Uploading disable-transport.mkv.mp4…

2021-10-30 11:02 UTC, commy2 commented
https://user-images.githubusercontent.com/6576312/139530289-21c9a5dc-f551-4749-b0e4-ff0f0977b829.mp4

2021-10-30 13:38 UTC, commy2 commented
https://user-images.githubusercontent.com/6576312/139534974-549c1674-81eb-4e09-b794-dc74e199902f.mp4

2021-11-05 14:24 UTC, Jundiyy commented
Good work on it so far 👍 I still think a small reduction in size is better, 0.85 makes it a bit too big for the WFs/ADs. Also for the new TechWF
![AT + WF](https://user-images.githubusercontent.com/79164303/140525771-c24a22cb-ab20-4bea-af80-25552d11ce5a.png)

Top Right is China WF
Bottom Right is USA WF
Top Left is TechWF
Bottom Left is GLA AD

2021-11-05 14:24 UTC, Jundiyy commented
Good work on it so far 👍 I still think a small reduction in size is better, 0.85 makes it a bit too big for the WFs/ADs. Also for the new TechWF
![AT + WF](https://user-images.githubusercontent.com/79164303/140525771-c24a22cb-ab20-4bea-af80-25552d11ce5a.png)

Top Right is China WF
Bottom Right is USA WF
Top Left is TechWF
Bottom Left is GLA AD

2021-11-20 12:08 UTC, commy2 commented
Uploading death.mp4…

2021-11-20 12:09 UTC, commy2 commented
https://user-images.githubusercontent.com/6576312/142725760-1990e7c6-bb20-46c1-992b-3785807b5981.mp4

2021-11-20 12:32 UTC, xezon reviewed
Where are these textures and models from? Do any files need to go into `GameFilesOriginal` folder for original reference? Were any DDS or TGA textures edited? If yes, then we should add the PSD source files.

2021-11-20 14:08 UTC, commy2 commented
Models are edited from the base game AVAmbib.w3d / AVAmbib_A.w3d (door) model. Textures are from base game avambhib.dss, converted to .tga, slightly edited, and exported as .dds again.

2021-11-20 14:29 UTC, xezon commented
Ok for the texture I highly recommend to add the TGA source. It is better than DDS, because DDS is lossy format while TGA is lossless and thus can be re-edited in the future. We will then compress TGA (and PSD) to DDS in build step.

2021-11-20 14:32 UTC, commy2 commented
They're here:
[avamphib_d.tga](https://github.com/xezon/GeneralsGamePatch/pull/601/files#diff-1fecbc381aaffb794f25ba073ca2834c4bedb45357370be3e3fb804b507a6797)
and
[avamphib_d1.tga](https://github.com/xezon/GeneralsGamePatch/pull/601/files#diff-50a1792a5a1eda445ca62a0b776ced039fce9b7e21f54c9759ccbaf40b54e492)

2021-11-20 14:34 UTC, commy2 commented
Though they're made from the base game `avamphib.dds`. I don't think the source for that is around anywhere.

2021-11-20 14:34 UTC, xezon commented
Ok you added the source and compiled textures. That should be ok for now. We can remove the DDS later then.

2021-11-20 14:48 UTC, xezon commented on Patch104pZH/Scripts/MAKE_Patch104pZH.bat
> +    xcopy /y    "%GameFilesDir%\Art\Textures\SAAmphibiousTransport_L.dds" "%GeneratedBigFilesUnpackedDir%\%BigName%\Art\Textures\"
SAAmphibiousTransport.dds and SAAmphibiousTransport_L.dds appear to be not be part of this change list. If game can load the tga's, then you could link to them here. I suspect game cannot load layered TGA. So if TGA is layered (which it should be), then must add DDS files for now.

2021-11-20 14:57 UTC, commy2 commented on Patch104pZH/Scripts/MAKE_Patch104pZH.bat
> +    xcopy /y    "%GameFilesDir%\Art\Textures\SAAmphibiousTransport_L.dds" "%GeneratedBigFilesUnpackedDir%\%BigName%\Art\Textures\"
These don't have DDS. All buttons/portraits are TGA. I just messed up the file extension.

2021-11-20 15:14 UTC, xezon approved these changes

2021-11-21 11:39 UTC, commy2 commented
- [ ] geometry too small
- [ ] more parts coming apart when destroyed
- [ ] damage texture improvements
- [ ] button doesn't use button art yet
- [ ] text

2021-11-21 11:39 UTC, xezon commented
![shot_20211121_122440_2](https://user-images.githubusercontent.com/4720891/142760310-161ee891-f453-4465-b527-e9bb4df72070.jpg)

2021-11-21 11:41 UTC, xezon commented
It is not so easy to replicate original damage look. Needs very dark patches on texture.
![shot_20211121_123244_3](https://user-images.githubusercontent.com/4720891/142760329-8717b96d-b443-4093-8f95-b8ec45c72d7e.jpg)

2022-01-01 15:54 UTC, xezon requested changes
New unit needs several more fixes as illustrated above.

2022-08-28 07:39 UTC, closed without merging