Add the Tech War Factory.
TheSuperHackers/GeneralsGamePatch pull request #605
Opened 2021-10-31 13:51 UTC by Jundiyy

Unfinished ZH Tech building, brought over from NProject, fully working.
Still needs a commandset, but will do this once we have added command buttons to the unused units.

Also needs the cameo pics added to ZH files. I will upload them here as not sure how we will do this.

2021-10-31 13:53 UTC, Jundiyy commented
[SMUserInterface512_003.zip](https://github.com/xezon/GeneralsGamePatch/files/7448948/SMUserInterface512_003.zip)

Tech War Factory pic can be seen on the bottom line, second to the right.

[MDUserInterface512.zip](https://github.com/xezon/GeneralsGamePatch/files/7448949/MDUserInterface512.zip)

The code used in NProject is this, of course we would need to change this depending how we implement the cameo.
`MappedImage SSTechFact_L
  Texture = SMUserInterface512_003.tga
  TextureWidth = 512
  TextureHeight = 512
  Coords = Left:245 Top:393 Right:365 Bottom:489
  Status = NONE
End`

2021-10-31 16:52 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/TechBuildings.ini
> +    IgnoreConditionStates = SNOW NIGHT
This line is superfluous here.

2021-10-31 16:52 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/TechBuildings.ini
> +    IgnoreConditionStates = SNOW NIGHT DAMAGED REALLYDAMAGED
Same.

2021-10-31 16:53 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/TechBuildings.ini
> +    IgnoreConditionStates = SNOW NIGHT DAMAGED REALLYDAMAGED
Same...

2021-10-31 16:53 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
> +  ;14 =
We don't need all those commented lines.

2021-10-31 16:55 UTC, Jundiyy commented on Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
> +  ;14 =
I was going to add the units in but was waiting for them to go through from Xezon. They will be filled up.

2021-10-31 16:58 UTC, Jundiyy commented on Patch104pZH/GameFilesEdited/Data/INI/Object/TechBuildings.ini
> +    IgnoreConditionStates = SNOW NIGHT
Which one? The `    IgnoreConditionStates = SNOW NIGHT`?

2021-10-31 16:58 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/TechBuildings.ini
> +    IgnoreConditionStates = SNOW NIGHT
Yes, that is the line the comment is on.

2021-10-31 17:02 UTC, Jundiyy commented on Patch104pZH/GameFilesEdited/Data/INI/Object/TechBuildings.ini
> +    IgnoreConditionStates = SNOW NIGHT
okay will remove, does it not need them?

2021-10-31 17:02 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/Object/TechBuildings.ini
> +    IgnoreConditionStates = SNOW NIGHT
Remove it. It does nothing and does not belong there.

2021-11-06 17:46 UTC, commy2 commented
- [ ] needs ui text ("War Factory" as placeholder currently)

The ruin looks exactly like the badly damaged building, but without flag. We didn't like this for the Repair Bay, but I guess we do not have a rubble model, right?

2021-11-06 19:07 UTC, commy2 approved these changes

2021-11-21 11:50 UTC, xezon requested changes

2021-11-21 11:50 UTC, xezon commented on Patch104pZH/Scripts/MAKE_Patch104pZH.bat
> +    xcopy /y    "%GameFilesDir%\Art\Textures\SSTechWarFactory_L.tga" "%GeneratedBigFilesUnpackedDir%\%BigName%\Art\Textures\"
The W3D Models and DDS textures are not added to the big file here, so they will not show correctly in game.

2021-11-21 11:52 UTC, commy2 commented on Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SSTechWarFactory.ini
> +End
Should go in  `Patch104pZH/GameFilesEdited/Data/INI/MappedImages/HandCreated/` folder now, with the rest.

2022-08-28 07:39 UTC, closed without merging